// ===========================================================
// RTL generated by ActiveCore framework
// Date: 2024-09-28 21:29:54
// Copyright Alexander Antonov <antonov.alex.alex@gmail.com>
// ===========================================================

`include "Neuromorphic_design.svh"

module Neuromorphic_design (
	input logic unsigned [0:0] clk_i
	, input logic unsigned [0:0] rst_i
);


logic unsigned [31:0] input_spike;

logic unsigned [31:0] gensticky_input_spike;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_input_spike <= 32'd0;
		end
	else
		begin
		gensticky_input_spike <= input_spike;
		end


always_comb
	begin
	input_spike = gensticky_input_spike;
	// Buffering globals
	// Processing dlychains
	// fifo_in buffering
	// subproc fifo_in buffering
	// Payload logic
	input_spike = 32'd1;
	end


endmodule
