// ===========================================================
// RTL generated by ActiveCore framework
// Date: 2025-02-25 16:58:03
// Copyright Alexander Antonov <antonov.alex.alex@gmail.com>
// ===========================================================

`ifndef __Neuromorphic_design_h_
`define __Neuromorphic_design_h_

`endif // __Neuromorphic_design_h_
