// ===========================================================
// RTL generated by ActiveCore framework
// Date: 2025-10-26 15:07:55
// Copyright Alexander Antonov <antonov.alex.alex@gmail.com>
// ===========================================================

`include "neuromorphic_core.svh"

module neuromorphic_core (
	input logic unsigned [0:0] clk_i
	, input logic unsigned [0:0] rst_i
	, input logic unsigned [0:0] wr_spike_in
	, input logic unsigned [31:0] wr_data_spike_in
	, output logic unsigned [0:0] full_spike_in
	, input logic unsigned [0:0] rd_spike_out
	, output logic unsigned [31:0] rd_data_spike_out
	, output logic unsigned [0:0] empty_spike_out
	, output logic unsigned [5:0] adr_w_l1
	, input logic unsigned [7:0] dat_w_l1
	, output logic unsigned [0:0] en_w_l1
	, input logic unsigned [11:0] cfg_threshold_i
	, input logic unsigned [7:0] cfg_leakage_i
	, input logic unsigned [31:0] cfg_baseAddr_i
	, input logic unsigned [15:0] cfg_postsynCount_i
	, input logic unsigned [31:0] cfg_layerBase_i [4:0]
	, input logic unsigned [0:0] en_core
);


logic unsigned [7:0] rd_credit_spike_in;
logic unsigned [7:0] rd_credit_spike_out;
logic unsigned [15:0] neur_acc;
logic unsigned [31:0] tick;
logic unsigned [31:0] tg0_period;
logic unsigned [31:0] tg0_counter;
logic unsigned [31:0] tg0_last;
logic unsigned [31:0] tg0_next;
logic unsigned [0:0] rd_spike_in;
logic unsigned [31:0] rd_data_spike_in;
logic unsigned [0:0] empty_spike_in;
logic unsigned [31:0] mem_spike_in [64:0];
logic unsigned [5:0] wptr_spike_in;
logic unsigned [5:0] rptr_spike_in;
logic unsigned [5:0] wptr_n_spike_in;
logic unsigned [5:0] rptr_n_spike_in;
logic unsigned [0:0] full_r_spike_in;
logic unsigned [0:0] full_n_spike_in;
logic unsigned [0:0] empty_n_spike_in;
logic unsigned [7:0] credit_spike_in [2:0];
logic unsigned [0:0] act_spike_in;
logic unsigned [0:0] wr_en_spike_in;
logic unsigned [7:0] wr_credit_spike_in;
logic unsigned [0:0] we_spike_out;
logic unsigned [31:0] wr_data_spike_out;
logic unsigned [0:0] full_spike_out;
logic unsigned [31:0] mem_spike_out [64:0];
logic unsigned [5:0] wptr_spike_out;
logic unsigned [5:0] rptr_spike_out;
logic unsigned [5:0] wptr_n_spike_out;
logic unsigned [5:0] rptr_n_spike_out;
logic unsigned [0:0] full_n_spike_out;
logic unsigned [0:0] empty_r_spike_out;
logic unsigned [0:0] empty_n_spike_out;
logic unsigned [7:0] credit_spike_out [2:0];
logic unsigned [0:0] act_spike_out;
logic unsigned [0:0] wr_en_spike_out;
logic unsigned [7:0] wr_credit_spike_out;
logic unsigned [15:0] mem_Vmemb [8:0];
logic unsigned [2:0] rd_idx_Vmemb;
logic unsigned [15:0] rd_data_Vmemb;
logic unsigned [2:0] wr_idx_Vmemb;
logic unsigned [15:0] wr_data_Vmemb;
logic unsigned [0:0] we_Vmemb;
logic unsigned [5:0] adr_w_l1_r;
logic unsigned [7:0] dat_w_l1_r;
logic unsigned [0:0] en_w_l1_r;
logic unsigned [11:0] cfg_threshold_r;
logic unsigned [7:0] cfg_leakage_r;
logic unsigned [31:0] cfg_baseAddr_r;
logic unsigned [15:0] cfg_postsynCount_r;
logic unsigned [31:0] cfg_layerBase_r [4:0];
logic unsigned [0:0] start_sel0;
logic unsigned [2:0] preidx_sel0;
logic unsigned [0:0] busy_sel0;
logic unsigned [0:0] done_sel0;
logic unsigned [2:0] postidx_sel0;
logic unsigned [2:0] prelatched_sel0;
logic unsigned [0:0] step_en_sel0;
logic unsigned [0:0] state_sel0;
logic unsigned [0:0] state_n_sel0;
logic unsigned [0:0] syn_gate_stub;
logic unsigned [0:0] syn_busy;
logic unsigned [0:0] syn_done;
logic unsigned [2:0] syn_pre;
logic unsigned [1:0] syn_st;
logic unsigned [1:0] syn_stn;
logic unsigned [0:0] neur_start;
logic unsigned [0:0] neur_busy;
logic unsigned [0:0] neur_done;
logic unsigned [2:0] neur_idx;
logic unsigned [1:0] neur_st;
logic unsigned [1:0] neur_stn;
logic unsigned [0:0] emit_start;
logic unsigned [0:0] emit_busy;
logic unsigned [0:0] emit_done;
logic unsigned [2:0] emit_idx;
logic unsigned [0:0] emit_fired;
logic unsigned [1:0] emit_st;
logic unsigned [1:0] emit_stn;
logic unsigned [0:0] reg_en_core;
logic unsigned [2:0] core_state;
logic unsigned [2:0] core_stateN;
logic unsigned [0:0] core_neur_start;
logic unsigned [0:0] core_emit_start;
logic unsigned [0:0] core_syn_gate;
logic unsigned [0:0] gen181_cyclix_genvar;
logic unsigned [0:0] gen182_cyclix_genvar;
logic unsigned [0:0] gen183_cyclix_genvar;
logic unsigned [32:0] gen184_cyclix_genvar;
logic unsigned [0:0] gen185_cyclix_genvar;
logic unsigned [0:0] gen186_cyclix_genvar;
logic unsigned [0:0] gen187_cyclix_genvar;
logic unsigned [0:0] gen188_cyclix_genvar;
logic unsigned [0:0] gen189_cyclix_genvar;
logic unsigned [0:0] gen190_cyclix_genvar;
logic unsigned [0:0] gen191_cyclix_genvar;
logic unsigned [32:0] gen192_cyclix_genvar;
logic unsigned [0:0] gen193_cyclix_genvar;
logic unsigned [1:0] gen194_cyclix_genvar;
logic unsigned [0:0] gen195_cyclix_genvar;
logic unsigned [0:0] gen196_cyclix_genvar;
logic unsigned [32:0] gen197_cyclix_genvar;
logic unsigned [0:0] gen198_cyclix_genvar;
logic unsigned [0:0] gen199_cyclix_genvar;
logic unsigned [0:0] gen200_cyclix_genvar;
logic unsigned [0:0] gen201_cyclix_genvar;
logic unsigned [32:0] gen202_cyclix_genvar;
logic unsigned [0:0] gen203_cyclix_genvar;
logic unsigned [0:0] gen204_cyclix_genvar;
logic unsigned [32:0] gen205_cyclix_genvar;
logic unsigned [0:0] gen206_cyclix_genvar;
logic unsigned [0:0] gen207_cyclix_genvar;
logic unsigned [0:0] gen208_cyclix_genvar;
logic unsigned [0:0] gen209_cyclix_genvar;
logic unsigned [0:0] gen210_cyclix_genvar;
logic unsigned [0:0] gen211_cyclix_genvar;
logic unsigned [32:0] gen212_cyclix_genvar;
logic unsigned [32:0] gen213_cyclix_genvar;
logic unsigned [0:0] gen214_cyclix_genvar;
logic unsigned [0:0] gen215_cyclix_genvar;
logic unsigned [32:0] gen216_cyclix_genvar;
logic unsigned [32:0] gen217_cyclix_genvar;
logic unsigned [0:0] gen218_cyclix_genvar;
logic unsigned [0:0] gen219_cyclix_genvar;
logic unsigned [0:0] gen220_cyclix_genvar;
logic unsigned [0:0] gen221_cyclix_genvar;
logic unsigned [32:0] gen222_cyclix_genvar;
logic unsigned [0:0] gen223_cyclix_genvar;
logic unsigned [0:0] gen224_cyclix_genvar;
logic unsigned [0:0] gen225_cyclix_genvar;
logic unsigned [0:0] gen226_cyclix_genvar;
logic unsigned [0:0] gen227_cyclix_genvar;
logic unsigned [0:0] gen228_cyclix_genvar;
logic unsigned [0:0] gen229_cyclix_genvar;
logic unsigned [0:0] gen230_cyclix_genvar;
logic unsigned [0:0] gen231_cyclix_genvar;
logic unsigned [32:0] gen232_cyclix_genvar;
logic unsigned [0:0] gen233_cyclix_genvar;
logic unsigned [1:0] gen234_cyclix_genvar;
logic unsigned [0:0] gen235_cyclix_genvar;
logic unsigned [0:0] gen236_cyclix_genvar;
logic unsigned [32:0] gen237_cyclix_genvar;
logic unsigned [0:0] gen238_cyclix_genvar;
logic unsigned [0:0] gen239_cyclix_genvar;
logic unsigned [0:0] gen240_cyclix_genvar;
logic unsigned [32:0] gen241_cyclix_genvar;
logic unsigned [0:0] gen242_cyclix_genvar;
logic unsigned [32:0] gen243_cyclix_genvar;
logic unsigned [0:0] gen244_cyclix_genvar;
logic unsigned [0:0] gen245_cyclix_genvar;
logic unsigned [0:0] gen246_cyclix_genvar;
logic unsigned [0:0] gen247_cyclix_genvar;
logic unsigned [0:0] gen248_cyclix_genvar;
logic unsigned [0:0] gen249_cyclix_genvar;
logic unsigned [32:0] gen250_cyclix_genvar;
logic unsigned [32:0] gen251_cyclix_genvar;
logic unsigned [0:0] gen252_cyclix_genvar;
logic unsigned [0:0] gen253_cyclix_genvar;
logic unsigned [32:0] gen254_cyclix_genvar;
logic unsigned [32:0] gen255_cyclix_genvar;
logic unsigned [0:0] gen256_cyclix_genvar;
logic unsigned [0:0] gen257_cyclix_genvar;
logic unsigned [0:0] gen258_cyclix_genvar;
logic unsigned [32:0] gen259_cyclix_genvar;
logic unsigned [0:0] gen260_cyclix_genvar;
logic unsigned [0:0] gen261_cyclix_genvar;
logic unsigned [0:0] gen262_cyclix_genvar;
logic unsigned [0:0] gen263_cyclix_genvar;
logic unsigned [0:0] gen264_cyclix_genvar;
logic unsigned [0:0] gen265_cyclix_genvar;
logic unsigned [0:0] gen266_cyclix_genvar;
logic unsigned [0:0] gen267_cyclix_genvar;
logic unsigned [0:0] gen268_cyclix_genvar;
logic unsigned [0:0] gen269_cyclix_genvar;
logic unsigned [18:0] gen270_cyclix_genvar;
logic unsigned [19:0] gen271_cyclix_genvar;
logic unsigned [32:0] gen272_cyclix_genvar;
logic unsigned [0:0] gen273_cyclix_genvar;
logic unsigned [0:0] gen274_cyclix_genvar;
logic unsigned [32:0] gen275_cyclix_genvar;
logic unsigned [0:0] gen276_cyclix_genvar;
logic unsigned [0:0] gen277_cyclix_genvar;
logic unsigned [0:0] gen278_cyclix_genvar;
logic unsigned [32:0] gen279_cyclix_genvar;
logic unsigned [0:0] gen280_cyclix_genvar;
logic unsigned [0:0] gen281_cyclix_genvar;
logic unsigned [0:0] gen282_cyclix_genvar;
logic unsigned [0:0] gen283_cyclix_genvar;
logic unsigned [0:0] gen284_cyclix_genvar;
logic unsigned [0:0] gen285_cyclix_genvar;
logic unsigned [0:0] gen286_cyclix_genvar;
logic unsigned [0:0] gen287_cyclix_genvar;
logic unsigned [0:0] gen288_cyclix_genvar;
logic unsigned [0:0] gen289_cyclix_genvar;
logic unsigned [0:0] gen290_cyclix_genvar;
logic unsigned [0:0] gen291_cyclix_genvar;
logic unsigned [0:0] gen292_cyclix_genvar;
logic unsigned [0:0] gen293_cyclix_genvar;
logic unsigned [16:0] gen294_cyclix_genvar;
logic unsigned [0:0] gen295_cyclix_genvar;
logic unsigned [0:0] gen296_cyclix_genvar;
logic unsigned [0:0] gen297_cyclix_genvar;
logic unsigned [0:0] gen298_cyclix_genvar;
logic unsigned [0:0] gen299_cyclix_genvar;
logic unsigned [0:0] gen300_cyclix_genvar;
logic unsigned [0:0] gen301_cyclix_genvar;
logic unsigned [0:0] gen302_cyclix_genvar;
logic unsigned [0:0] gen303_cyclix_genvar;
logic unsigned [0:0] gen304_cyclix_genvar;
logic unsigned [16:0] gen305_cyclix_genvar;
logic unsigned [15:0] gen306_cyclix_genvar;
logic unsigned [32:0] gen307_cyclix_genvar;
logic unsigned [0:0] gen308_cyclix_genvar;
logic unsigned [0:0] gen309_cyclix_genvar;
logic unsigned [0:0] gen310_cyclix_genvar;
logic unsigned [32:0] gen311_cyclix_genvar;
logic unsigned [0:0] gen312_cyclix_genvar;
logic unsigned [0:0] gen313_cyclix_genvar;
logic unsigned [0:0] gen314_cyclix_genvar;
logic unsigned [0:0] gen315_cyclix_genvar;
logic unsigned [0:0] gen316_cyclix_genvar;
logic unsigned [0:0] gen317_cyclix_genvar;
logic unsigned [0:0] gen318_cyclix_genvar;
logic unsigned [0:0] gen319_cyclix_genvar;
logic unsigned [0:0] gen320_cyclix_genvar;
logic unsigned [0:0] gen321_cyclix_genvar;
logic unsigned [0:0] gen322_cyclix_genvar;
logic unsigned [0:0] gen323_cyclix_genvar;
logic unsigned [0:0] gen324_cyclix_genvar;
logic unsigned [0:0] gen325_cyclix_genvar;
logic unsigned [0:0] gen326_cyclix_genvar;
logic unsigned [0:0] gen327_cyclix_genvar;
logic unsigned [0:0] gen328_cyclix_genvar;
logic unsigned [0:0] gen329_cyclix_genvar;
logic unsigned [0:0] gen330_cyclix_genvar;
logic unsigned [0:0] gen331_cyclix_genvar;
logic unsigned [0:0] gen332_cyclix_genvar;
logic unsigned [32:0] gen333_cyclix_genvar;
logic unsigned [0:0] gen334_cyclix_genvar;
logic unsigned [0:0] gen335_cyclix_genvar;
logic unsigned [0:0] gen336_cyclix_genvar;
logic unsigned [32:0] gen337_cyclix_genvar;
logic unsigned [0:0] gen338_cyclix_genvar;
logic unsigned [0:0] gen339_cyclix_genvar;
logic unsigned [0:0] gen340_cyclix_genvar;
logic unsigned [0:0] gen341_cyclix_genvar;
logic unsigned [0:0] gen342_cyclix_genvar;
logic unsigned [0:0] gen343_cyclix_genvar;
logic unsigned [0:0] gen344_cyclix_genvar;
logic unsigned [0:0] gen345_cyclix_genvar;
logic unsigned [0:0] gen346_cyclix_genvar;
logic unsigned [0:0] gen347_cyclix_genvar;
logic unsigned [0:0] gen348_cyclix_genvar;
logic unsigned [0:0] gen349_cyclix_genvar;
logic unsigned [0:0] gen350_cyclix_genvar;
logic unsigned [0:0] gen351_cyclix_genvar;
logic unsigned [0:0] gen352_cyclix_genvar;
logic unsigned [0:0] gen353_cyclix_genvar;
logic unsigned [0:0] gen354_cyclix_genvar;
logic unsigned [0:0] gen355_cyclix_genvar;
logic unsigned [0:0] gen356_cyclix_genvar;
logic unsigned [0:0] gen357_cyclix_genvar;
logic unsigned [0:0] gen358_cyclix_genvar;
logic unsigned [0:0] gen359_cyclix_genvar;
logic unsigned [0:0] gen360_cyclix_genvar;
logic unsigned [0:0] gen361_cyclix_genvar;
logic unsigned [0:0] gen0_rtl_var;
logic unsigned [0:0] gen1_rtl_var;
logic unsigned [0:0] gen2_rtl_var;
logic unsigned [0:0] gen3_rtl_var;
logic unsigned [0:0] gen4_rtl_var;
logic unsigned [0:0] gen5_rtl_var;
logic unsigned [0:0] gen6_rtl_var;
logic unsigned [0:0] gen7_rtl_var;
logic unsigned [0:0] gen8_rtl_var;
logic unsigned [0:0] gen9_rtl_var;
logic unsigned [0:0] gen10_rtl_var;
logic unsigned [0:0] gen11_rtl_var;
logic unsigned [0:0] gen12_rtl_var;
logic unsigned [0:0] gen13_rtl_var;
logic unsigned [0:0] gen14_rtl_var;
logic unsigned [0:0] gen15_rtl_var;
logic unsigned [0:0] gen16_rtl_var;
logic unsigned [0:0] gen17_rtl_var;
logic unsigned [0:0] gen18_rtl_var;
logic unsigned [0:0] gen19_rtl_var;
logic unsigned [0:0] gen20_rtl_var;
logic unsigned [0:0] gen21_rtl_var;
logic unsigned [0:0] gen22_rtl_var;
logic unsigned [0:0] gen23_rtl_var;
logic unsigned [0:0] gen24_rtl_var;
logic unsigned [0:0] gen25_rtl_var;
logic unsigned [0:0] gen26_rtl_var;
logic unsigned [0:0] gen27_rtl_var;
logic unsigned [0:0] gen28_rtl_var;
logic unsigned [0:0] gen29_rtl_var;
logic unsigned [0:0] gen30_rtl_var;
logic unsigned [0:0] gen31_rtl_var;
logic unsigned [0:0] gen32_rtl_var;
logic unsigned [0:0] gen33_rtl_var;
logic unsigned [0:0] gen34_rtl_var;
logic unsigned [0:0] gen35_rtl_var;
logic unsigned [0:0] gen36_rtl_var;
logic unsigned [0:0] gen37_rtl_var;
logic unsigned [0:0] gen38_rtl_var;
logic unsigned [0:0] gen39_rtl_var;
logic unsigned [0:0] gen40_rtl_var;
logic unsigned [0:0] gen41_rtl_var;
logic unsigned [0:0] gen42_rtl_var;
logic unsigned [0:0] gen43_rtl_var;
logic unsigned [0:0] gen44_rtl_var;
logic unsigned [0:0] gen45_rtl_var;
logic unsigned [0:0] gen46_rtl_var;
logic unsigned [0:0] gen47_rtl_var;
logic unsigned [0:0] gen48_rtl_var;
logic unsigned [0:0] gen49_rtl_var;
logic unsigned [0:0] gen50_rtl_var;
logic unsigned [0:0] gen51_rtl_var;
logic unsigned [0:0] gen52_rtl_var;
logic unsigned [0:0] gen53_rtl_var;
logic unsigned [0:0] gen54_rtl_var;
logic unsigned [0:0] gen55_rtl_var;
logic unsigned [0:0] gen56_rtl_var;
logic unsigned [0:0] gen57_rtl_var;
logic unsigned [0:0] gen58_rtl_var;
logic unsigned [0:0] gen59_rtl_var;
logic unsigned [0:0] gen60_rtl_var;
logic unsigned [0:0] gen61_rtl_var;
logic unsigned [0:0] gen62_rtl_var;
logic unsigned [0:0] gen63_rtl_var;
logic unsigned [0:0] gen64_rtl_var;

logic unsigned [31:0] gensticky_tick;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_tick <= 32'd0;
		end
	else
		begin
		gensticky_tick <= tick;
		end

logic unsigned [31:0] gensticky_tg0_period;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_tg0_period <= 32'd100000;
		end
	else
		begin
		gensticky_tg0_period <= tg0_period;
		end

logic unsigned [31:0] gensticky_tg0_counter;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_tg0_counter <= 32'd0;
		end
	else
		begin
		gensticky_tg0_counter <= tg0_counter;
		end

logic unsigned [31:0] gensticky_tg0_last;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_tg0_last <= 32'd99999;
		end
	else
		begin
		gensticky_tg0_last <= tg0_last;
		end

logic unsigned [31:0] gensticky_tg0_next;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_tg0_next <= 32'd0;
		end
	else
		begin
		gensticky_tg0_next <= tg0_next;
		end

logic unsigned [0:0] gensticky_rd_spike_in;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_rd_spike_in <= 32'd0;
		end
	else
		begin
		gensticky_rd_spike_in <= rd_spike_in;
		end

logic unsigned [31:0] gensticky_rd_data_spike_in;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_rd_data_spike_in <= 32'd0;
		end
	else
		begin
		gensticky_rd_data_spike_in <= rd_data_spike_in;
		end

logic unsigned [0:0] gensticky_empty_spike_in;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_empty_spike_in <= 32'd1;
		end
	else
		begin
		gensticky_empty_spike_in <= empty_spike_in;
		end

logic unsigned [31:0] gensticky_mem_spike_in [64:0];
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_mem_spike_in[0] <= 32'd0;
		gensticky_mem_spike_in[1] <= 32'd0;
		gensticky_mem_spike_in[2] <= 32'd0;
		gensticky_mem_spike_in[3] <= 32'd0;
		gensticky_mem_spike_in[4] <= 32'd0;
		gensticky_mem_spike_in[5] <= 32'd0;
		gensticky_mem_spike_in[6] <= 32'd0;
		gensticky_mem_spike_in[7] <= 32'd0;
		gensticky_mem_spike_in[8] <= 32'd0;
		gensticky_mem_spike_in[9] <= 32'd0;
		gensticky_mem_spike_in[10] <= 32'd0;
		gensticky_mem_spike_in[11] <= 32'd0;
		gensticky_mem_spike_in[12] <= 32'd0;
		gensticky_mem_spike_in[13] <= 32'd0;
		gensticky_mem_spike_in[14] <= 32'd0;
		gensticky_mem_spike_in[15] <= 32'd0;
		gensticky_mem_spike_in[16] <= 32'd0;
		gensticky_mem_spike_in[17] <= 32'd0;
		gensticky_mem_spike_in[18] <= 32'd0;
		gensticky_mem_spike_in[19] <= 32'd0;
		gensticky_mem_spike_in[20] <= 32'd0;
		gensticky_mem_spike_in[21] <= 32'd0;
		gensticky_mem_spike_in[22] <= 32'd0;
		gensticky_mem_spike_in[23] <= 32'd0;
		gensticky_mem_spike_in[24] <= 32'd0;
		gensticky_mem_spike_in[25] <= 32'd0;
		gensticky_mem_spike_in[26] <= 32'd0;
		gensticky_mem_spike_in[27] <= 32'd0;
		gensticky_mem_spike_in[28] <= 32'd0;
		gensticky_mem_spike_in[29] <= 32'd0;
		gensticky_mem_spike_in[30] <= 32'd0;
		gensticky_mem_spike_in[31] <= 32'd0;
		gensticky_mem_spike_in[32] <= 32'd0;
		gensticky_mem_spike_in[33] <= 32'd0;
		gensticky_mem_spike_in[34] <= 32'd0;
		gensticky_mem_spike_in[35] <= 32'd0;
		gensticky_mem_spike_in[36] <= 32'd0;
		gensticky_mem_spike_in[37] <= 32'd0;
		gensticky_mem_spike_in[38] <= 32'd0;
		gensticky_mem_spike_in[39] <= 32'd0;
		gensticky_mem_spike_in[40] <= 32'd0;
		gensticky_mem_spike_in[41] <= 32'd0;
		gensticky_mem_spike_in[42] <= 32'd0;
		gensticky_mem_spike_in[43] <= 32'd0;
		gensticky_mem_spike_in[44] <= 32'd0;
		gensticky_mem_spike_in[45] <= 32'd0;
		gensticky_mem_spike_in[46] <= 32'd0;
		gensticky_mem_spike_in[47] <= 32'd0;
		gensticky_mem_spike_in[48] <= 32'd0;
		gensticky_mem_spike_in[49] <= 32'd0;
		gensticky_mem_spike_in[50] <= 32'd0;
		gensticky_mem_spike_in[51] <= 32'd0;
		gensticky_mem_spike_in[52] <= 32'd0;
		gensticky_mem_spike_in[53] <= 32'd0;
		gensticky_mem_spike_in[54] <= 32'd0;
		gensticky_mem_spike_in[55] <= 32'd0;
		gensticky_mem_spike_in[56] <= 32'd0;
		gensticky_mem_spike_in[57] <= 32'd0;
		gensticky_mem_spike_in[58] <= 32'd0;
		gensticky_mem_spike_in[59] <= 32'd0;
		gensticky_mem_spike_in[60] <= 32'd0;
		gensticky_mem_spike_in[61] <= 32'd0;
		gensticky_mem_spike_in[62] <= 32'd0;
		gensticky_mem_spike_in[63] <= 32'd0;
		gensticky_mem_spike_in[64] <= 32'd0;
		end
	else
		begin
		gensticky_mem_spike_in[0] <= mem_spike_in[0];
		gensticky_mem_spike_in[1] <= mem_spike_in[1];
		gensticky_mem_spike_in[2] <= mem_spike_in[2];
		gensticky_mem_spike_in[3] <= mem_spike_in[3];
		gensticky_mem_spike_in[4] <= mem_spike_in[4];
		gensticky_mem_spike_in[5] <= mem_spike_in[5];
		gensticky_mem_spike_in[6] <= mem_spike_in[6];
		gensticky_mem_spike_in[7] <= mem_spike_in[7];
		gensticky_mem_spike_in[8] <= mem_spike_in[8];
		gensticky_mem_spike_in[9] <= mem_spike_in[9];
		gensticky_mem_spike_in[10] <= mem_spike_in[10];
		gensticky_mem_spike_in[11] <= mem_spike_in[11];
		gensticky_mem_spike_in[12] <= mem_spike_in[12];
		gensticky_mem_spike_in[13] <= mem_spike_in[13];
		gensticky_mem_spike_in[14] <= mem_spike_in[14];
		gensticky_mem_spike_in[15] <= mem_spike_in[15];
		gensticky_mem_spike_in[16] <= mem_spike_in[16];
		gensticky_mem_spike_in[17] <= mem_spike_in[17];
		gensticky_mem_spike_in[18] <= mem_spike_in[18];
		gensticky_mem_spike_in[19] <= mem_spike_in[19];
		gensticky_mem_spike_in[20] <= mem_spike_in[20];
		gensticky_mem_spike_in[21] <= mem_spike_in[21];
		gensticky_mem_spike_in[22] <= mem_spike_in[22];
		gensticky_mem_spike_in[23] <= mem_spike_in[23];
		gensticky_mem_spike_in[24] <= mem_spike_in[24];
		gensticky_mem_spike_in[25] <= mem_spike_in[25];
		gensticky_mem_spike_in[26] <= mem_spike_in[26];
		gensticky_mem_spike_in[27] <= mem_spike_in[27];
		gensticky_mem_spike_in[28] <= mem_spike_in[28];
		gensticky_mem_spike_in[29] <= mem_spike_in[29];
		gensticky_mem_spike_in[30] <= mem_spike_in[30];
		gensticky_mem_spike_in[31] <= mem_spike_in[31];
		gensticky_mem_spike_in[32] <= mem_spike_in[32];
		gensticky_mem_spike_in[33] <= mem_spike_in[33];
		gensticky_mem_spike_in[34] <= mem_spike_in[34];
		gensticky_mem_spike_in[35] <= mem_spike_in[35];
		gensticky_mem_spike_in[36] <= mem_spike_in[36];
		gensticky_mem_spike_in[37] <= mem_spike_in[37];
		gensticky_mem_spike_in[38] <= mem_spike_in[38];
		gensticky_mem_spike_in[39] <= mem_spike_in[39];
		gensticky_mem_spike_in[40] <= mem_spike_in[40];
		gensticky_mem_spike_in[41] <= mem_spike_in[41];
		gensticky_mem_spike_in[42] <= mem_spike_in[42];
		gensticky_mem_spike_in[43] <= mem_spike_in[43];
		gensticky_mem_spike_in[44] <= mem_spike_in[44];
		gensticky_mem_spike_in[45] <= mem_spike_in[45];
		gensticky_mem_spike_in[46] <= mem_spike_in[46];
		gensticky_mem_spike_in[47] <= mem_spike_in[47];
		gensticky_mem_spike_in[48] <= mem_spike_in[48];
		gensticky_mem_spike_in[49] <= mem_spike_in[49];
		gensticky_mem_spike_in[50] <= mem_spike_in[50];
		gensticky_mem_spike_in[51] <= mem_spike_in[51];
		gensticky_mem_spike_in[52] <= mem_spike_in[52];
		gensticky_mem_spike_in[53] <= mem_spike_in[53];
		gensticky_mem_spike_in[54] <= mem_spike_in[54];
		gensticky_mem_spike_in[55] <= mem_spike_in[55];
		gensticky_mem_spike_in[56] <= mem_spike_in[56];
		gensticky_mem_spike_in[57] <= mem_spike_in[57];
		gensticky_mem_spike_in[58] <= mem_spike_in[58];
		gensticky_mem_spike_in[59] <= mem_spike_in[59];
		gensticky_mem_spike_in[60] <= mem_spike_in[60];
		gensticky_mem_spike_in[61] <= mem_spike_in[61];
		gensticky_mem_spike_in[62] <= mem_spike_in[62];
		gensticky_mem_spike_in[63] <= mem_spike_in[63];
		gensticky_mem_spike_in[64] <= mem_spike_in[64];
		end

logic unsigned [5:0] gensticky_wptr_spike_in;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_wptr_spike_in <= 32'd0;
		end
	else
		begin
		gensticky_wptr_spike_in <= wptr_spike_in;
		end

logic unsigned [5:0] gensticky_rptr_spike_in;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_rptr_spike_in <= 32'd0;
		end
	else
		begin
		gensticky_rptr_spike_in <= rptr_spike_in;
		end

logic unsigned [5:0] gensticky_wptr_n_spike_in;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_wptr_n_spike_in <= 32'd0;
		end
	else
		begin
		gensticky_wptr_n_spike_in <= wptr_n_spike_in;
		end

logic unsigned [5:0] gensticky_rptr_n_spike_in;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_rptr_n_spike_in <= 32'd0;
		end
	else
		begin
		gensticky_rptr_n_spike_in <= rptr_n_spike_in;
		end

logic unsigned [0:0] gensticky_full_r_spike_in;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_full_r_spike_in <= 32'd0;
		end
	else
		begin
		gensticky_full_r_spike_in <= full_r_spike_in;
		end

logic unsigned [0:0] gensticky_full_n_spike_in;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_full_n_spike_in <= 32'd0;
		end
	else
		begin
		gensticky_full_n_spike_in <= full_n_spike_in;
		end

logic unsigned [0:0] gensticky_empty_n_spike_in;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_empty_n_spike_in <= 32'd1;
		end
	else
		begin
		gensticky_empty_n_spike_in <= empty_n_spike_in;
		end

logic unsigned [7:0] gensticky_credit_spike_in [2:0];
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_credit_spike_in[0] <= 32'd0;
		gensticky_credit_spike_in[1] <= 32'd0;
		gensticky_credit_spike_in[2] <= 32'd0;
		end
	else
		begin
		gensticky_credit_spike_in[0] <= credit_spike_in[0];
		gensticky_credit_spike_in[1] <= credit_spike_in[1];
		gensticky_credit_spike_in[2] <= credit_spike_in[2];
		end

logic unsigned [0:0] gensticky_act_spike_in;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_act_spike_in <= 32'd0;
		end
	else
		begin
		gensticky_act_spike_in <= act_spike_in;
		end

logic unsigned [0:0] gensticky_wr_en_spike_in;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_wr_en_spike_in <= 32'd0;
		end
	else
		begin
		gensticky_wr_en_spike_in <= wr_en_spike_in;
		end

logic unsigned [7:0] gensticky_wr_credit_spike_in;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_wr_credit_spike_in <= 32'd0;
		end
	else
		begin
		gensticky_wr_credit_spike_in <= wr_credit_spike_in;
		end

logic unsigned [0:0] gensticky_we_spike_out;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_we_spike_out <= 32'd0;
		end
	else
		begin
		gensticky_we_spike_out <= we_spike_out;
		end

logic unsigned [31:0] gensticky_wr_data_spike_out;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_wr_data_spike_out <= 32'd0;
		end
	else
		begin
		gensticky_wr_data_spike_out <= wr_data_spike_out;
		end

logic unsigned [0:0] gensticky_full_spike_out;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_full_spike_out <= 32'd0;
		end
	else
		begin
		gensticky_full_spike_out <= full_spike_out;
		end

logic unsigned [31:0] gensticky_mem_spike_out [64:0];
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_mem_spike_out[0] <= 32'd0;
		gensticky_mem_spike_out[1] <= 32'd0;
		gensticky_mem_spike_out[2] <= 32'd0;
		gensticky_mem_spike_out[3] <= 32'd0;
		gensticky_mem_spike_out[4] <= 32'd0;
		gensticky_mem_spike_out[5] <= 32'd0;
		gensticky_mem_spike_out[6] <= 32'd0;
		gensticky_mem_spike_out[7] <= 32'd0;
		gensticky_mem_spike_out[8] <= 32'd0;
		gensticky_mem_spike_out[9] <= 32'd0;
		gensticky_mem_spike_out[10] <= 32'd0;
		gensticky_mem_spike_out[11] <= 32'd0;
		gensticky_mem_spike_out[12] <= 32'd0;
		gensticky_mem_spike_out[13] <= 32'd0;
		gensticky_mem_spike_out[14] <= 32'd0;
		gensticky_mem_spike_out[15] <= 32'd0;
		gensticky_mem_spike_out[16] <= 32'd0;
		gensticky_mem_spike_out[17] <= 32'd0;
		gensticky_mem_spike_out[18] <= 32'd0;
		gensticky_mem_spike_out[19] <= 32'd0;
		gensticky_mem_spike_out[20] <= 32'd0;
		gensticky_mem_spike_out[21] <= 32'd0;
		gensticky_mem_spike_out[22] <= 32'd0;
		gensticky_mem_spike_out[23] <= 32'd0;
		gensticky_mem_spike_out[24] <= 32'd0;
		gensticky_mem_spike_out[25] <= 32'd0;
		gensticky_mem_spike_out[26] <= 32'd0;
		gensticky_mem_spike_out[27] <= 32'd0;
		gensticky_mem_spike_out[28] <= 32'd0;
		gensticky_mem_spike_out[29] <= 32'd0;
		gensticky_mem_spike_out[30] <= 32'd0;
		gensticky_mem_spike_out[31] <= 32'd0;
		gensticky_mem_spike_out[32] <= 32'd0;
		gensticky_mem_spike_out[33] <= 32'd0;
		gensticky_mem_spike_out[34] <= 32'd0;
		gensticky_mem_spike_out[35] <= 32'd0;
		gensticky_mem_spike_out[36] <= 32'd0;
		gensticky_mem_spike_out[37] <= 32'd0;
		gensticky_mem_spike_out[38] <= 32'd0;
		gensticky_mem_spike_out[39] <= 32'd0;
		gensticky_mem_spike_out[40] <= 32'd0;
		gensticky_mem_spike_out[41] <= 32'd0;
		gensticky_mem_spike_out[42] <= 32'd0;
		gensticky_mem_spike_out[43] <= 32'd0;
		gensticky_mem_spike_out[44] <= 32'd0;
		gensticky_mem_spike_out[45] <= 32'd0;
		gensticky_mem_spike_out[46] <= 32'd0;
		gensticky_mem_spike_out[47] <= 32'd0;
		gensticky_mem_spike_out[48] <= 32'd0;
		gensticky_mem_spike_out[49] <= 32'd0;
		gensticky_mem_spike_out[50] <= 32'd0;
		gensticky_mem_spike_out[51] <= 32'd0;
		gensticky_mem_spike_out[52] <= 32'd0;
		gensticky_mem_spike_out[53] <= 32'd0;
		gensticky_mem_spike_out[54] <= 32'd0;
		gensticky_mem_spike_out[55] <= 32'd0;
		gensticky_mem_spike_out[56] <= 32'd0;
		gensticky_mem_spike_out[57] <= 32'd0;
		gensticky_mem_spike_out[58] <= 32'd0;
		gensticky_mem_spike_out[59] <= 32'd0;
		gensticky_mem_spike_out[60] <= 32'd0;
		gensticky_mem_spike_out[61] <= 32'd0;
		gensticky_mem_spike_out[62] <= 32'd0;
		gensticky_mem_spike_out[63] <= 32'd0;
		gensticky_mem_spike_out[64] <= 32'd0;
		end
	else
		begin
		gensticky_mem_spike_out[0] <= mem_spike_out[0];
		gensticky_mem_spike_out[1] <= mem_spike_out[1];
		gensticky_mem_spike_out[2] <= mem_spike_out[2];
		gensticky_mem_spike_out[3] <= mem_spike_out[3];
		gensticky_mem_spike_out[4] <= mem_spike_out[4];
		gensticky_mem_spike_out[5] <= mem_spike_out[5];
		gensticky_mem_spike_out[6] <= mem_spike_out[6];
		gensticky_mem_spike_out[7] <= mem_spike_out[7];
		gensticky_mem_spike_out[8] <= mem_spike_out[8];
		gensticky_mem_spike_out[9] <= mem_spike_out[9];
		gensticky_mem_spike_out[10] <= mem_spike_out[10];
		gensticky_mem_spike_out[11] <= mem_spike_out[11];
		gensticky_mem_spike_out[12] <= mem_spike_out[12];
		gensticky_mem_spike_out[13] <= mem_spike_out[13];
		gensticky_mem_spike_out[14] <= mem_spike_out[14];
		gensticky_mem_spike_out[15] <= mem_spike_out[15];
		gensticky_mem_spike_out[16] <= mem_spike_out[16];
		gensticky_mem_spike_out[17] <= mem_spike_out[17];
		gensticky_mem_spike_out[18] <= mem_spike_out[18];
		gensticky_mem_spike_out[19] <= mem_spike_out[19];
		gensticky_mem_spike_out[20] <= mem_spike_out[20];
		gensticky_mem_spike_out[21] <= mem_spike_out[21];
		gensticky_mem_spike_out[22] <= mem_spike_out[22];
		gensticky_mem_spike_out[23] <= mem_spike_out[23];
		gensticky_mem_spike_out[24] <= mem_spike_out[24];
		gensticky_mem_spike_out[25] <= mem_spike_out[25];
		gensticky_mem_spike_out[26] <= mem_spike_out[26];
		gensticky_mem_spike_out[27] <= mem_spike_out[27];
		gensticky_mem_spike_out[28] <= mem_spike_out[28];
		gensticky_mem_spike_out[29] <= mem_spike_out[29];
		gensticky_mem_spike_out[30] <= mem_spike_out[30];
		gensticky_mem_spike_out[31] <= mem_spike_out[31];
		gensticky_mem_spike_out[32] <= mem_spike_out[32];
		gensticky_mem_spike_out[33] <= mem_spike_out[33];
		gensticky_mem_spike_out[34] <= mem_spike_out[34];
		gensticky_mem_spike_out[35] <= mem_spike_out[35];
		gensticky_mem_spike_out[36] <= mem_spike_out[36];
		gensticky_mem_spike_out[37] <= mem_spike_out[37];
		gensticky_mem_spike_out[38] <= mem_spike_out[38];
		gensticky_mem_spike_out[39] <= mem_spike_out[39];
		gensticky_mem_spike_out[40] <= mem_spike_out[40];
		gensticky_mem_spike_out[41] <= mem_spike_out[41];
		gensticky_mem_spike_out[42] <= mem_spike_out[42];
		gensticky_mem_spike_out[43] <= mem_spike_out[43];
		gensticky_mem_spike_out[44] <= mem_spike_out[44];
		gensticky_mem_spike_out[45] <= mem_spike_out[45];
		gensticky_mem_spike_out[46] <= mem_spike_out[46];
		gensticky_mem_spike_out[47] <= mem_spike_out[47];
		gensticky_mem_spike_out[48] <= mem_spike_out[48];
		gensticky_mem_spike_out[49] <= mem_spike_out[49];
		gensticky_mem_spike_out[50] <= mem_spike_out[50];
		gensticky_mem_spike_out[51] <= mem_spike_out[51];
		gensticky_mem_spike_out[52] <= mem_spike_out[52];
		gensticky_mem_spike_out[53] <= mem_spike_out[53];
		gensticky_mem_spike_out[54] <= mem_spike_out[54];
		gensticky_mem_spike_out[55] <= mem_spike_out[55];
		gensticky_mem_spike_out[56] <= mem_spike_out[56];
		gensticky_mem_spike_out[57] <= mem_spike_out[57];
		gensticky_mem_spike_out[58] <= mem_spike_out[58];
		gensticky_mem_spike_out[59] <= mem_spike_out[59];
		gensticky_mem_spike_out[60] <= mem_spike_out[60];
		gensticky_mem_spike_out[61] <= mem_spike_out[61];
		gensticky_mem_spike_out[62] <= mem_spike_out[62];
		gensticky_mem_spike_out[63] <= mem_spike_out[63];
		gensticky_mem_spike_out[64] <= mem_spike_out[64];
		end

logic unsigned [5:0] gensticky_wptr_spike_out;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_wptr_spike_out <= 32'd0;
		end
	else
		begin
		gensticky_wptr_spike_out <= wptr_spike_out;
		end

logic unsigned [5:0] gensticky_rptr_spike_out;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_rptr_spike_out <= 32'd0;
		end
	else
		begin
		gensticky_rptr_spike_out <= rptr_spike_out;
		end

logic unsigned [5:0] gensticky_wptr_n_spike_out;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_wptr_n_spike_out <= 32'd0;
		end
	else
		begin
		gensticky_wptr_n_spike_out <= wptr_n_spike_out;
		end

logic unsigned [5:0] gensticky_rptr_n_spike_out;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_rptr_n_spike_out <= 32'd0;
		end
	else
		begin
		gensticky_rptr_n_spike_out <= rptr_n_spike_out;
		end

logic unsigned [0:0] gensticky_full_n_spike_out;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_full_n_spike_out <= 32'd0;
		end
	else
		begin
		gensticky_full_n_spike_out <= full_n_spike_out;
		end

logic unsigned [0:0] gensticky_empty_r_spike_out;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_empty_r_spike_out <= 32'd1;
		end
	else
		begin
		gensticky_empty_r_spike_out <= empty_r_spike_out;
		end

logic unsigned [0:0] gensticky_empty_n_spike_out;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_empty_n_spike_out <= 32'd1;
		end
	else
		begin
		gensticky_empty_n_spike_out <= empty_n_spike_out;
		end

logic unsigned [7:0] gensticky_credit_spike_out [2:0];
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_credit_spike_out[0] <= 32'd0;
		gensticky_credit_spike_out[1] <= 32'd0;
		gensticky_credit_spike_out[2] <= 32'd0;
		end
	else
		begin
		gensticky_credit_spike_out[0] <= credit_spike_out[0];
		gensticky_credit_spike_out[1] <= credit_spike_out[1];
		gensticky_credit_spike_out[2] <= credit_spike_out[2];
		end

logic unsigned [0:0] gensticky_act_spike_out;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_act_spike_out <= 32'd0;
		end
	else
		begin
		gensticky_act_spike_out <= act_spike_out;
		end

logic unsigned [0:0] gensticky_wr_en_spike_out;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_wr_en_spike_out <= 32'd0;
		end
	else
		begin
		gensticky_wr_en_spike_out <= wr_en_spike_out;
		end

logic unsigned [7:0] gensticky_wr_credit_spike_out;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_wr_credit_spike_out <= 32'd0;
		end
	else
		begin
		gensticky_wr_credit_spike_out <= wr_credit_spike_out;
		end

logic unsigned [15:0] gensticky_mem_Vmemb [8:0];
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_mem_Vmemb[0] <= 32'd0;
		gensticky_mem_Vmemb[1] <= 32'd0;
		gensticky_mem_Vmemb[2] <= 32'd0;
		gensticky_mem_Vmemb[3] <= 32'd0;
		gensticky_mem_Vmemb[4] <= 32'd0;
		gensticky_mem_Vmemb[5] <= 32'd0;
		gensticky_mem_Vmemb[6] <= 32'd0;
		gensticky_mem_Vmemb[7] <= 32'd0;
		gensticky_mem_Vmemb[8] <= 32'd0;
		end
	else
		begin
		gensticky_mem_Vmemb[0] <= mem_Vmemb[0];
		gensticky_mem_Vmemb[1] <= mem_Vmemb[1];
		gensticky_mem_Vmemb[2] <= mem_Vmemb[2];
		gensticky_mem_Vmemb[3] <= mem_Vmemb[3];
		gensticky_mem_Vmemb[4] <= mem_Vmemb[4];
		gensticky_mem_Vmemb[5] <= mem_Vmemb[5];
		gensticky_mem_Vmemb[6] <= mem_Vmemb[6];
		gensticky_mem_Vmemb[7] <= mem_Vmemb[7];
		gensticky_mem_Vmemb[8] <= mem_Vmemb[8];
		end

logic unsigned [2:0] gensticky_rd_idx_Vmemb;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_rd_idx_Vmemb <= 32'd0;
		end
	else
		begin
		gensticky_rd_idx_Vmemb <= rd_idx_Vmemb;
		end

logic unsigned [15:0] gensticky_rd_data_Vmemb;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_rd_data_Vmemb <= 32'd0;
		end
	else
		begin
		gensticky_rd_data_Vmemb <= rd_data_Vmemb;
		end

logic unsigned [2:0] gensticky_wr_idx_Vmemb;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_wr_idx_Vmemb <= 32'd0;
		end
	else
		begin
		gensticky_wr_idx_Vmemb <= wr_idx_Vmemb;
		end

logic unsigned [15:0] gensticky_wr_data_Vmemb;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_wr_data_Vmemb <= 32'd0;
		end
	else
		begin
		gensticky_wr_data_Vmemb <= wr_data_Vmemb;
		end

logic unsigned [0:0] gensticky_we_Vmemb;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_we_Vmemb <= 32'd0;
		end
	else
		begin
		gensticky_we_Vmemb <= we_Vmemb;
		end

logic unsigned [5:0] gensticky_adr_w_l1_r;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_adr_w_l1_r <= 32'd0;
		end
	else
		begin
		gensticky_adr_w_l1_r <= adr_w_l1_r;
		end

logic unsigned [7:0] gensticky_dat_w_l1_r;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_dat_w_l1_r <= 32'd0;
		end
	else
		begin
		gensticky_dat_w_l1_r <= dat_w_l1_r;
		end

logic unsigned [0:0] gensticky_en_w_l1_r;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_en_w_l1_r <= 32'd0;
		end
	else
		begin
		gensticky_en_w_l1_r <= en_w_l1_r;
		end

logic unsigned [11:0] gensticky_cfg_threshold_r;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_cfg_threshold_r <= 32'd0;
		end
	else
		begin
		gensticky_cfg_threshold_r <= cfg_threshold_r;
		end

logic unsigned [7:0] gensticky_cfg_leakage_r;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_cfg_leakage_r <= 32'd0;
		end
	else
		begin
		gensticky_cfg_leakage_r <= cfg_leakage_r;
		end

logic unsigned [31:0] gensticky_cfg_baseAddr_r;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_cfg_baseAddr_r <= 32'd0;
		end
	else
		begin
		gensticky_cfg_baseAddr_r <= cfg_baseAddr_r;
		end

logic unsigned [15:0] gensticky_cfg_postsynCount_r;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_cfg_postsynCount_r <= 32'd0;
		end
	else
		begin
		gensticky_cfg_postsynCount_r <= cfg_postsynCount_r;
		end

logic unsigned [31:0] gensticky_cfg_layerBase_r [4:0];
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_cfg_layerBase_r[0] <= 32'd0;
		gensticky_cfg_layerBase_r[1] <= 32'd0;
		gensticky_cfg_layerBase_r[2] <= 32'd0;
		gensticky_cfg_layerBase_r[3] <= 32'd0;
		gensticky_cfg_layerBase_r[4] <= 32'd0;
		end
	else
		begin
		gensticky_cfg_layerBase_r[0] <= cfg_layerBase_r[0];
		gensticky_cfg_layerBase_r[1] <= cfg_layerBase_r[1];
		gensticky_cfg_layerBase_r[2] <= cfg_layerBase_r[2];
		gensticky_cfg_layerBase_r[3] <= cfg_layerBase_r[3];
		gensticky_cfg_layerBase_r[4] <= cfg_layerBase_r[4];
		end

logic unsigned [0:0] gensticky_start_sel0;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_start_sel0 <= 32'd0;
		end
	else
		begin
		gensticky_start_sel0 <= start_sel0;
		end

logic unsigned [2:0] gensticky_preidx_sel0;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_preidx_sel0 <= 32'd0;
		end
	else
		begin
		gensticky_preidx_sel0 <= preidx_sel0;
		end

logic unsigned [0:0] gensticky_busy_sel0;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_busy_sel0 <= 32'd0;
		end
	else
		begin
		gensticky_busy_sel0 <= busy_sel0;
		end

logic unsigned [0:0] gensticky_done_sel0;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_done_sel0 <= 32'd0;
		end
	else
		begin
		gensticky_done_sel0 <= done_sel0;
		end

logic unsigned [2:0] gensticky_postidx_sel0;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_postidx_sel0 <= 32'd0;
		end
	else
		begin
		gensticky_postidx_sel0 <= postidx_sel0;
		end

logic unsigned [2:0] gensticky_prelatched_sel0;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_prelatched_sel0 <= 32'd0;
		end
	else
		begin
		gensticky_prelatched_sel0 <= prelatched_sel0;
		end

logic unsigned [0:0] gensticky_step_en_sel0;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_step_en_sel0 <= 32'd0;
		end
	else
		begin
		gensticky_step_en_sel0 <= step_en_sel0;
		end

logic unsigned [0:0] gensticky_state_sel0;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_state_sel0 <= 32'd0;
		end
	else
		begin
		gensticky_state_sel0 <= state_sel0;
		end

logic unsigned [0:0] gensticky_state_n_sel0;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_state_n_sel0 <= 32'd0;
		end
	else
		begin
		gensticky_state_n_sel0 <= state_n_sel0;
		end

logic unsigned [0:0] gensticky_syn_gate_stub;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_syn_gate_stub <= 32'd0;
		end
	else
		begin
		gensticky_syn_gate_stub <= syn_gate_stub;
		end

logic unsigned [0:0] gensticky_syn_busy;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_syn_busy <= 32'd0;
		end
	else
		begin
		gensticky_syn_busy <= syn_busy;
		end

logic unsigned [0:0] gensticky_syn_done;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_syn_done <= 32'd0;
		end
	else
		begin
		gensticky_syn_done <= syn_done;
		end

logic unsigned [2:0] gensticky_syn_pre;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_syn_pre <= 32'd0;
		end
	else
		begin
		gensticky_syn_pre <= syn_pre;
		end

logic unsigned [1:0] gensticky_syn_st;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_syn_st <= 32'd0;
		end
	else
		begin
		gensticky_syn_st <= syn_st;
		end

logic unsigned [1:0] gensticky_syn_stn;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_syn_stn <= 32'd0;
		end
	else
		begin
		gensticky_syn_stn <= syn_stn;
		end

logic unsigned [0:0] gensticky_neur_start;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_neur_start <= 32'd0;
		end
	else
		begin
		gensticky_neur_start <= neur_start;
		end

logic unsigned [0:0] gensticky_neur_busy;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_neur_busy <= 32'd0;
		end
	else
		begin
		gensticky_neur_busy <= neur_busy;
		end

logic unsigned [0:0] gensticky_neur_done;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_neur_done <= 32'd0;
		end
	else
		begin
		gensticky_neur_done <= neur_done;
		end

logic unsigned [2:0] gensticky_neur_idx;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_neur_idx <= 32'd0;
		end
	else
		begin
		gensticky_neur_idx <= neur_idx;
		end

logic unsigned [1:0] gensticky_neur_st;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_neur_st <= 32'd0;
		end
	else
		begin
		gensticky_neur_st <= neur_st;
		end

logic unsigned [1:0] gensticky_neur_stn;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_neur_stn <= 32'd0;
		end
	else
		begin
		gensticky_neur_stn <= neur_stn;
		end

logic unsigned [0:0] gensticky_emit_start;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_emit_start <= 32'd0;
		end
	else
		begin
		gensticky_emit_start <= emit_start;
		end

logic unsigned [0:0] gensticky_emit_busy;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_emit_busy <= 32'd0;
		end
	else
		begin
		gensticky_emit_busy <= emit_busy;
		end

logic unsigned [0:0] gensticky_emit_done;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_emit_done <= 32'd0;
		end
	else
		begin
		gensticky_emit_done <= emit_done;
		end

logic unsigned [2:0] gensticky_emit_idx;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_emit_idx <= 32'd0;
		end
	else
		begin
		gensticky_emit_idx <= emit_idx;
		end

logic unsigned [0:0] gensticky_emit_fired;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_emit_fired <= 32'd0;
		end
	else
		begin
		gensticky_emit_fired <= emit_fired;
		end

logic unsigned [1:0] gensticky_emit_st;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_emit_st <= 32'd0;
		end
	else
		begin
		gensticky_emit_st <= emit_st;
		end

logic unsigned [1:0] gensticky_emit_stn;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_emit_stn <= 32'd0;
		end
	else
		begin
		gensticky_emit_stn <= emit_stn;
		end

logic unsigned [0:0] gensticky_reg_en_core;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_reg_en_core <= 32'd0;
		end
	else
		begin
		gensticky_reg_en_core <= reg_en_core;
		end

logic unsigned [2:0] gensticky_core_state;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_core_state <= 32'd0;
		end
	else
		begin
		gensticky_core_state <= core_state;
		end

logic unsigned [2:0] gensticky_core_stateN;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_core_stateN <= 32'd0;
		end
	else
		begin
		gensticky_core_stateN <= core_stateN;
		end

logic unsigned [0:0] gensticky_core_neur_start;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_core_neur_start <= 32'd0;
		end
	else
		begin
		gensticky_core_neur_start <= core_neur_start;
		end

logic unsigned [0:0] gensticky_core_emit_start;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_core_emit_start <= 32'd0;
		end
	else
		begin
		gensticky_core_emit_start <= core_emit_start;
		end

logic unsigned [0:0] gensticky_core_syn_gate;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_core_syn_gate <= 32'd0;
		end
	else
		begin
		gensticky_core_syn_gate <= core_syn_gate;
		end


always_comb
	begin
	tick = 32'd0;
	tg0_counter = 32'd0;
	gen184_cyclix_genvar = 32'd0;
	tg0_next = 32'd0;
	gen187_cyclix_genvar = 32'd0;
	act_spike_in = 32'd0;
	mem_spike_in[0] = 32'd0;
	mem_spike_in[1] = 32'd0;
	mem_spike_in[2] = 32'd0;
	mem_spike_in[3] = 32'd0;
	mem_spike_in[4] = 32'd0;
	mem_spike_in[5] = 32'd0;
	mem_spike_in[6] = 32'd0;
	mem_spike_in[7] = 32'd0;
	mem_spike_in[8] = 32'd0;
	mem_spike_in[9] = 32'd0;
	mem_spike_in[10] = 32'd0;
	mem_spike_in[11] = 32'd0;
	mem_spike_in[12] = 32'd0;
	mem_spike_in[13] = 32'd0;
	mem_spike_in[14] = 32'd0;
	mem_spike_in[15] = 32'd0;
	mem_spike_in[16] = 32'd0;
	mem_spike_in[17] = 32'd0;
	mem_spike_in[18] = 32'd0;
	mem_spike_in[19] = 32'd0;
	mem_spike_in[20] = 32'd0;
	mem_spike_in[21] = 32'd0;
	mem_spike_in[22] = 32'd0;
	mem_spike_in[23] = 32'd0;
	mem_spike_in[24] = 32'd0;
	mem_spike_in[25] = 32'd0;
	mem_spike_in[26] = 32'd0;
	mem_spike_in[27] = 32'd0;
	mem_spike_in[28] = 32'd0;
	mem_spike_in[29] = 32'd0;
	mem_spike_in[30] = 32'd0;
	mem_spike_in[31] = 32'd0;
	mem_spike_in[32] = 32'd0;
	mem_spike_in[33] = 32'd0;
	mem_spike_in[34] = 32'd0;
	mem_spike_in[35] = 32'd0;
	mem_spike_in[36] = 32'd0;
	mem_spike_in[37] = 32'd0;
	mem_spike_in[38] = 32'd0;
	mem_spike_in[39] = 32'd0;
	mem_spike_in[40] = 32'd0;
	mem_spike_in[41] = 32'd0;
	mem_spike_in[42] = 32'd0;
	mem_spike_in[43] = 32'd0;
	mem_spike_in[44] = 32'd0;
	mem_spike_in[45] = 32'd0;
	mem_spike_in[46] = 32'd0;
	mem_spike_in[47] = 32'd0;
	mem_spike_in[48] = 32'd0;
	mem_spike_in[49] = 32'd0;
	mem_spike_in[50] = 32'd0;
	mem_spike_in[51] = 32'd0;
	mem_spike_in[52] = 32'd0;
	mem_spike_in[53] = 32'd0;
	mem_spike_in[54] = 32'd0;
	mem_spike_in[55] = 32'd0;
	mem_spike_in[56] = 32'd0;
	mem_spike_in[57] = 32'd0;
	mem_spike_in[58] = 32'd0;
	mem_spike_in[59] = 32'd0;
	mem_spike_in[60] = 32'd0;
	mem_spike_in[61] = 32'd0;
	mem_spike_in[62] = 32'd0;
	mem_spike_in[63] = 32'd0;
	mem_spike_in[64] = 32'd0;
	gen192_cyclix_genvar = 32'd0;
	credit_spike_in[0] = 32'd0;
	credit_spike_in[1] = 32'd0;
	credit_spike_in[2] = 32'd0;
	gen200_cyclix_genvar = 32'd0;
	gen201_cyclix_genvar = 32'd0;
	gen202_cyclix_genvar = 32'd0;
	gen204_cyclix_genvar = 32'd0;
	empty_n_spike_in = 32'd1;
	gen197_cyclix_genvar = 32'd0;
	rptr_n_spike_in = 32'd0;
	full_n_spike_in = 32'd0;
	gen198_cyclix_genvar = 32'd0;
	gen199_cyclix_genvar = 32'd0;
	gen5_rtl_var = 32'd0;
	gen203_cyclix_genvar = 32'd0;
	gen6_rtl_var = 32'd0;
	gen205_cyclix_genvar = 32'd0;
	gen206_cyclix_genvar = 32'd0;
	gen207_cyclix_genvar = 32'd0;
	gen7_rtl_var = 32'd0;
	gen209_cyclix_genvar = 32'd0;
	gen212_cyclix_genvar = 32'd0;
	wptr_n_spike_in = 32'd0;
	gen213_cyclix_genvar = 32'd0;
	gen214_cyclix_genvar = 32'd0;
	gen215_cyclix_genvar = 32'd0;
	gen10_rtl_var = 32'd0;
	gen220_cyclix_genvar = 32'd0;
	gen221_cyclix_genvar = 32'd0;
	gen222_cyclix_genvar = 32'd0;
	gen224_cyclix_genvar = 32'd0;
	gen195_cyclix_genvar = 32'd0;
	gen196_cyclix_genvar = 32'd0;
	gen4_rtl_var = 32'd0;
	gen208_cyclix_genvar = 32'd0;
	gen8_rtl_var = 32'd0;
	gen210_cyclix_genvar = 32'd0;
	gen211_cyclix_genvar = 32'd0;
	gen9_rtl_var = 32'd0;
	gen216_cyclix_genvar = 32'd0;
	gen217_cyclix_genvar = 32'd0;
	gen218_cyclix_genvar = 32'd0;
	gen219_cyclix_genvar = 32'd0;
	gen11_rtl_var = 32'd0;
	gen223_cyclix_genvar = 32'd0;
	gen12_rtl_var = 32'd0;
	gen227_cyclix_genvar = 32'd0;
	act_spike_out = 32'd0;
	mem_spike_out[0] = 32'd0;
	mem_spike_out[1] = 32'd0;
	mem_spike_out[2] = 32'd0;
	mem_spike_out[3] = 32'd0;
	mem_spike_out[4] = 32'd0;
	mem_spike_out[5] = 32'd0;
	mem_spike_out[6] = 32'd0;
	mem_spike_out[7] = 32'd0;
	mem_spike_out[8] = 32'd0;
	mem_spike_out[9] = 32'd0;
	mem_spike_out[10] = 32'd0;
	mem_spike_out[11] = 32'd0;
	mem_spike_out[12] = 32'd0;
	mem_spike_out[13] = 32'd0;
	mem_spike_out[14] = 32'd0;
	mem_spike_out[15] = 32'd0;
	mem_spike_out[16] = 32'd0;
	mem_spike_out[17] = 32'd0;
	mem_spike_out[18] = 32'd0;
	mem_spike_out[19] = 32'd0;
	mem_spike_out[20] = 32'd0;
	mem_spike_out[21] = 32'd0;
	mem_spike_out[22] = 32'd0;
	mem_spike_out[23] = 32'd0;
	mem_spike_out[24] = 32'd0;
	mem_spike_out[25] = 32'd0;
	mem_spike_out[26] = 32'd0;
	mem_spike_out[27] = 32'd0;
	mem_spike_out[28] = 32'd0;
	mem_spike_out[29] = 32'd0;
	mem_spike_out[30] = 32'd0;
	mem_spike_out[31] = 32'd0;
	mem_spike_out[32] = 32'd0;
	mem_spike_out[33] = 32'd0;
	mem_spike_out[34] = 32'd0;
	mem_spike_out[35] = 32'd0;
	mem_spike_out[36] = 32'd0;
	mem_spike_out[37] = 32'd0;
	mem_spike_out[38] = 32'd0;
	mem_spike_out[39] = 32'd0;
	mem_spike_out[40] = 32'd0;
	mem_spike_out[41] = 32'd0;
	mem_spike_out[42] = 32'd0;
	mem_spike_out[43] = 32'd0;
	mem_spike_out[44] = 32'd0;
	mem_spike_out[45] = 32'd0;
	mem_spike_out[46] = 32'd0;
	mem_spike_out[47] = 32'd0;
	mem_spike_out[48] = 32'd0;
	mem_spike_out[49] = 32'd0;
	mem_spike_out[50] = 32'd0;
	mem_spike_out[51] = 32'd0;
	mem_spike_out[52] = 32'd0;
	mem_spike_out[53] = 32'd0;
	mem_spike_out[54] = 32'd0;
	mem_spike_out[55] = 32'd0;
	mem_spike_out[56] = 32'd0;
	mem_spike_out[57] = 32'd0;
	mem_spike_out[58] = 32'd0;
	mem_spike_out[59] = 32'd0;
	mem_spike_out[60] = 32'd0;
	mem_spike_out[61] = 32'd0;
	mem_spike_out[62] = 32'd0;
	mem_spike_out[63] = 32'd0;
	mem_spike_out[64] = 32'd0;
	gen232_cyclix_genvar = 32'd0;
	credit_spike_out[0] = 32'd0;
	credit_spike_out[1] = 32'd0;
	credit_spike_out[2] = 32'd0;
	gen241_cyclix_genvar = 32'd0;
	empty_n_spike_out = 32'd1;
	gen237_cyclix_genvar = 32'd0;
	rptr_n_spike_out = 32'd0;
	full_n_spike_out = 32'd0;
	gen238_cyclix_genvar = 32'd0;
	gen239_cyclix_genvar = 32'd0;
	gen240_cyclix_genvar = 32'd0;
	gen16_rtl_var = 32'd0;
	gen242_cyclix_genvar = 32'd0;
	gen17_rtl_var = 32'd0;
	gen243_cyclix_genvar = 32'd0;
	gen244_cyclix_genvar = 32'd0;
	gen245_cyclix_genvar = 32'd0;
	gen18_rtl_var = 32'd0;
	gen247_cyclix_genvar = 32'd0;
	gen250_cyclix_genvar = 32'd0;
	wptr_n_spike_out = 32'd0;
	gen251_cyclix_genvar = 32'd0;
	gen252_cyclix_genvar = 32'd0;
	gen253_cyclix_genvar = 32'd0;
	gen21_rtl_var = 32'd0;
	gen259_cyclix_genvar = 32'd0;
	gen235_cyclix_genvar = 32'd0;
	gen236_cyclix_genvar = 32'd0;
	gen15_rtl_var = 32'd0;
	gen246_cyclix_genvar = 32'd0;
	gen19_rtl_var = 32'd0;
	gen248_cyclix_genvar = 32'd0;
	gen249_cyclix_genvar = 32'd0;
	gen20_rtl_var = 32'd0;
	gen254_cyclix_genvar = 32'd0;
	gen255_cyclix_genvar = 32'd0;
	gen256_cyclix_genvar = 32'd0;
	gen257_cyclix_genvar = 32'd0;
	gen258_cyclix_genvar = 32'd0;
	gen22_rtl_var = 32'd0;
	gen260_cyclix_genvar = 32'd0;
	gen23_rtl_var = 32'd0;
	mem_Vmemb[0] = 32'd0;
	mem_Vmemb[1] = 32'd0;
	mem_Vmemb[2] = 32'd0;
	mem_Vmemb[3] = 32'd0;
	mem_Vmemb[4] = 32'd0;
	mem_Vmemb[5] = 32'd0;
	mem_Vmemb[6] = 32'd0;
	mem_Vmemb[7] = 32'd0;
	mem_Vmemb[8] = 32'd0;
	prelatched_sel0 = 32'd0;
	postidx_sel0 = 32'd0;
	busy_sel0 = 32'd0;
	state_n_sel0 = 32'd0;
	gen266_cyclix_genvar = 32'd0;
	gen267_cyclix_genvar = 32'd0;
	gen26_rtl_var = 32'd0;
	done_sel0 = 32'd0;
	gen279_cyclix_genvar = 32'd0;
	gen275_cyclix_genvar = 32'd0;
	gen276_cyclix_genvar = 32'd0;
	gen277_cyclix_genvar = 32'd0;
	gen29_rtl_var = 32'd0;
	gen278_cyclix_genvar = 32'd0;
	gen30_rtl_var = 32'd0;
	gen270_cyclix_genvar = 32'd0;
	gen271_cyclix_genvar = 32'd0;
	gen272_cyclix_genvar = 32'd0;
	adr_w_l1_r = 32'd0;
	en_w_l1_r = 32'd0;
	gen273_cyclix_genvar = 32'd0;
	gen274_cyclix_genvar = 32'd0;
	gen28_rtl_var = 32'd0;
	rd_spike_in = 32'd0;
	syn_stn = 32'd0;
	syn_done = 32'd0;
	syn_busy = 32'd0;
	gen285_cyclix_genvar = 32'd0;
	gen286_cyclix_genvar = 32'd0;
	gen32_rtl_var = 32'd0;
	gen287_cyclix_genvar = 32'd0;
	gen33_rtl_var = 32'd0;
	syn_pre = 32'd0;
	preidx_sel0 = 32'd0;
	start_sel0 = 32'd0;
	we_Vmemb = 32'd0;
	rd_idx_Vmemb = 32'd0;
	gen294_cyclix_genvar = 32'd0;
	wr_idx_Vmemb = 32'd0;
	wr_data_Vmemb = 32'd0;
	gen295_cyclix_genvar = 32'd0;
	gen296_cyclix_genvar = 32'd0;
	gen37_rtl_var = 32'd0;
	neur_idx = 32'd0;
	neur_busy = 32'd0;
	neur_stn = 32'd0;
	gen299_cyclix_genvar = 32'd0;
	gen300_cyclix_genvar = 32'd0;
	gen39_rtl_var = 32'd0;
	neur_done = 32'd0;
	gen311_cyclix_genvar = 32'd0;
	neur_acc = 32'd0;
	gen305_cyclix_genvar = 32'd0;
	gen306_cyclix_genvar = 32'd0;
	gen307_cyclix_genvar = 32'd0;
	gen308_cyclix_genvar = 32'd0;
	gen309_cyclix_genvar = 32'd0;
	gen42_rtl_var = 32'd0;
	gen310_cyclix_genvar = 32'd0;
	gen43_rtl_var = 32'd0;
	emit_idx = 32'd0;
	emit_busy = 32'd0;
	emit_stn = 32'd0;
	gen314_cyclix_genvar = 32'd0;
	gen315_cyclix_genvar = 32'd0;
	gen45_rtl_var = 32'd0;
	we_spike_out = 32'd0;
	wr_data_spike_out = 32'd0;
	emit_fired = 32'd0;
	emit_done = 32'd0;
	gen337_cyclix_genvar = 32'd0;
	gen333_cyclix_genvar = 32'd0;
	gen334_cyclix_genvar = 32'd0;
	gen335_cyclix_genvar = 32'd0;
	gen51_rtl_var = 32'd0;
	gen336_cyclix_genvar = 32'd0;
	gen52_rtl_var = 32'd0;
	gen320_cyclix_genvar = 32'd0;
	gen321_cyclix_genvar = 32'd0;
	gen322_cyclix_genvar = 32'd0;
	gen323_cyclix_genvar = 32'd0;
	gen324_cyclix_genvar = 32'd0;
	gen325_cyclix_genvar = 32'd0;
	gen326_cyclix_genvar = 32'd0;
	gen48_rtl_var = 32'd0;
	gen327_cyclix_genvar = 32'd0;
	gen328_cyclix_genvar = 32'd0;
	gen329_cyclix_genvar = 32'd0;
	gen49_rtl_var = 32'd0;
	gen330_cyclix_genvar = 32'd0;
	gen331_cyclix_genvar = 32'd0;
	gen332_cyclix_genvar = 32'd0;
	gen50_rtl_var = 32'd0;
	core_stateN = 32'd0;
	gen340_cyclix_genvar = 32'd0;
	gen341_cyclix_genvar = 32'd0;
	gen54_rtl_var = 32'd0;
	core_syn_gate = 32'd0;
	gen344_cyclix_genvar = 32'd0;
	gen345_cyclix_genvar = 32'd0;
	gen56_rtl_var = 32'd0;
	gen348_cyclix_genvar = 32'd0;
	gen349_cyclix_genvar = 32'd0;
	gen58_rtl_var = 32'd0;
	core_neur_start = 32'd0;
	gen352_cyclix_genvar = 32'd0;
	gen353_cyclix_genvar = 32'd0;
	gen60_rtl_var = 32'd0;
	core_emit_start = 32'd0;
	gen356_cyclix_genvar = 32'd0;
	gen357_cyclix_genvar = 32'd0;
	gen62_rtl_var = 32'd0;
	gen360_cyclix_genvar = 32'd0;
	gen361_cyclix_genvar = 32'd0;
	gen64_rtl_var = 32'd0;
	tick = gensticky_tick;
	tg0_counter = gensticky_tg0_counter;
	tg0_next = gensticky_tg0_next;
	act_spike_in = gensticky_act_spike_in;
	wr_en_spike_in = gensticky_wr_en_spike_in;
	mem_spike_in[0] = gensticky_mem_spike_in[0];
	mem_spike_in[1] = gensticky_mem_spike_in[1];
	mem_spike_in[2] = gensticky_mem_spike_in[2];
	mem_spike_in[3] = gensticky_mem_spike_in[3];
	mem_spike_in[4] = gensticky_mem_spike_in[4];
	mem_spike_in[5] = gensticky_mem_spike_in[5];
	mem_spike_in[6] = gensticky_mem_spike_in[6];
	mem_spike_in[7] = gensticky_mem_spike_in[7];
	mem_spike_in[8] = gensticky_mem_spike_in[8];
	mem_spike_in[9] = gensticky_mem_spike_in[9];
	mem_spike_in[10] = gensticky_mem_spike_in[10];
	mem_spike_in[11] = gensticky_mem_spike_in[11];
	mem_spike_in[12] = gensticky_mem_spike_in[12];
	mem_spike_in[13] = gensticky_mem_spike_in[13];
	mem_spike_in[14] = gensticky_mem_spike_in[14];
	mem_spike_in[15] = gensticky_mem_spike_in[15];
	mem_spike_in[16] = gensticky_mem_spike_in[16];
	mem_spike_in[17] = gensticky_mem_spike_in[17];
	mem_spike_in[18] = gensticky_mem_spike_in[18];
	mem_spike_in[19] = gensticky_mem_spike_in[19];
	mem_spike_in[20] = gensticky_mem_spike_in[20];
	mem_spike_in[21] = gensticky_mem_spike_in[21];
	mem_spike_in[22] = gensticky_mem_spike_in[22];
	mem_spike_in[23] = gensticky_mem_spike_in[23];
	mem_spike_in[24] = gensticky_mem_spike_in[24];
	mem_spike_in[25] = gensticky_mem_spike_in[25];
	mem_spike_in[26] = gensticky_mem_spike_in[26];
	mem_spike_in[27] = gensticky_mem_spike_in[27];
	mem_spike_in[28] = gensticky_mem_spike_in[28];
	mem_spike_in[29] = gensticky_mem_spike_in[29];
	mem_spike_in[30] = gensticky_mem_spike_in[30];
	mem_spike_in[31] = gensticky_mem_spike_in[31];
	mem_spike_in[32] = gensticky_mem_spike_in[32];
	mem_spike_in[33] = gensticky_mem_spike_in[33];
	mem_spike_in[34] = gensticky_mem_spike_in[34];
	mem_spike_in[35] = gensticky_mem_spike_in[35];
	mem_spike_in[36] = gensticky_mem_spike_in[36];
	mem_spike_in[37] = gensticky_mem_spike_in[37];
	mem_spike_in[38] = gensticky_mem_spike_in[38];
	mem_spike_in[39] = gensticky_mem_spike_in[39];
	mem_spike_in[40] = gensticky_mem_spike_in[40];
	mem_spike_in[41] = gensticky_mem_spike_in[41];
	mem_spike_in[42] = gensticky_mem_spike_in[42];
	mem_spike_in[43] = gensticky_mem_spike_in[43];
	mem_spike_in[44] = gensticky_mem_spike_in[44];
	mem_spike_in[45] = gensticky_mem_spike_in[45];
	mem_spike_in[46] = gensticky_mem_spike_in[46];
	mem_spike_in[47] = gensticky_mem_spike_in[47];
	mem_spike_in[48] = gensticky_mem_spike_in[48];
	mem_spike_in[49] = gensticky_mem_spike_in[49];
	mem_spike_in[50] = gensticky_mem_spike_in[50];
	mem_spike_in[51] = gensticky_mem_spike_in[51];
	mem_spike_in[52] = gensticky_mem_spike_in[52];
	mem_spike_in[53] = gensticky_mem_spike_in[53];
	mem_spike_in[54] = gensticky_mem_spike_in[54];
	mem_spike_in[55] = gensticky_mem_spike_in[55];
	mem_spike_in[56] = gensticky_mem_spike_in[56];
	mem_spike_in[57] = gensticky_mem_spike_in[57];
	mem_spike_in[58] = gensticky_mem_spike_in[58];
	mem_spike_in[59] = gensticky_mem_spike_in[59];
	mem_spike_in[60] = gensticky_mem_spike_in[60];
	mem_spike_in[61] = gensticky_mem_spike_in[61];
	mem_spike_in[62] = gensticky_mem_spike_in[62];
	mem_spike_in[63] = gensticky_mem_spike_in[63];
	mem_spike_in[64] = gensticky_mem_spike_in[64];
	credit_spike_in[0] = gensticky_credit_spike_in[0];
	credit_spike_in[1] = gensticky_credit_spike_in[1];
	credit_spike_in[2] = gensticky_credit_spike_in[2];
	wr_credit_spike_in = gensticky_wr_credit_spike_in;
	rd_data_spike_in = gensticky_rd_data_spike_in;
	wptr_spike_in = gensticky_wptr_spike_in;
	rptr_spike_in = gensticky_rptr_spike_in;
	empty_spike_in = gensticky_empty_spike_in;
	full_r_spike_in = gensticky_full_r_spike_in;
	rptr_n_spike_in = gensticky_rptr_n_spike_in;
	full_n_spike_in = gensticky_full_n_spike_in;
	empty_n_spike_in = gensticky_empty_n_spike_in;
	wptr_n_spike_in = gensticky_wptr_n_spike_in;
	act_spike_out = gensticky_act_spike_out;
	wr_en_spike_out = gensticky_wr_en_spike_out;
	mem_spike_out[0] = gensticky_mem_spike_out[0];
	mem_spike_out[1] = gensticky_mem_spike_out[1];
	mem_spike_out[2] = gensticky_mem_spike_out[2];
	mem_spike_out[3] = gensticky_mem_spike_out[3];
	mem_spike_out[4] = gensticky_mem_spike_out[4];
	mem_spike_out[5] = gensticky_mem_spike_out[5];
	mem_spike_out[6] = gensticky_mem_spike_out[6];
	mem_spike_out[7] = gensticky_mem_spike_out[7];
	mem_spike_out[8] = gensticky_mem_spike_out[8];
	mem_spike_out[9] = gensticky_mem_spike_out[9];
	mem_spike_out[10] = gensticky_mem_spike_out[10];
	mem_spike_out[11] = gensticky_mem_spike_out[11];
	mem_spike_out[12] = gensticky_mem_spike_out[12];
	mem_spike_out[13] = gensticky_mem_spike_out[13];
	mem_spike_out[14] = gensticky_mem_spike_out[14];
	mem_spike_out[15] = gensticky_mem_spike_out[15];
	mem_spike_out[16] = gensticky_mem_spike_out[16];
	mem_spike_out[17] = gensticky_mem_spike_out[17];
	mem_spike_out[18] = gensticky_mem_spike_out[18];
	mem_spike_out[19] = gensticky_mem_spike_out[19];
	mem_spike_out[20] = gensticky_mem_spike_out[20];
	mem_spike_out[21] = gensticky_mem_spike_out[21];
	mem_spike_out[22] = gensticky_mem_spike_out[22];
	mem_spike_out[23] = gensticky_mem_spike_out[23];
	mem_spike_out[24] = gensticky_mem_spike_out[24];
	mem_spike_out[25] = gensticky_mem_spike_out[25];
	mem_spike_out[26] = gensticky_mem_spike_out[26];
	mem_spike_out[27] = gensticky_mem_spike_out[27];
	mem_spike_out[28] = gensticky_mem_spike_out[28];
	mem_spike_out[29] = gensticky_mem_spike_out[29];
	mem_spike_out[30] = gensticky_mem_spike_out[30];
	mem_spike_out[31] = gensticky_mem_spike_out[31];
	mem_spike_out[32] = gensticky_mem_spike_out[32];
	mem_spike_out[33] = gensticky_mem_spike_out[33];
	mem_spike_out[34] = gensticky_mem_spike_out[34];
	mem_spike_out[35] = gensticky_mem_spike_out[35];
	mem_spike_out[36] = gensticky_mem_spike_out[36];
	mem_spike_out[37] = gensticky_mem_spike_out[37];
	mem_spike_out[38] = gensticky_mem_spike_out[38];
	mem_spike_out[39] = gensticky_mem_spike_out[39];
	mem_spike_out[40] = gensticky_mem_spike_out[40];
	mem_spike_out[41] = gensticky_mem_spike_out[41];
	mem_spike_out[42] = gensticky_mem_spike_out[42];
	mem_spike_out[43] = gensticky_mem_spike_out[43];
	mem_spike_out[44] = gensticky_mem_spike_out[44];
	mem_spike_out[45] = gensticky_mem_spike_out[45];
	mem_spike_out[46] = gensticky_mem_spike_out[46];
	mem_spike_out[47] = gensticky_mem_spike_out[47];
	mem_spike_out[48] = gensticky_mem_spike_out[48];
	mem_spike_out[49] = gensticky_mem_spike_out[49];
	mem_spike_out[50] = gensticky_mem_spike_out[50];
	mem_spike_out[51] = gensticky_mem_spike_out[51];
	mem_spike_out[52] = gensticky_mem_spike_out[52];
	mem_spike_out[53] = gensticky_mem_spike_out[53];
	mem_spike_out[54] = gensticky_mem_spike_out[54];
	mem_spike_out[55] = gensticky_mem_spike_out[55];
	mem_spike_out[56] = gensticky_mem_spike_out[56];
	mem_spike_out[57] = gensticky_mem_spike_out[57];
	mem_spike_out[58] = gensticky_mem_spike_out[58];
	mem_spike_out[59] = gensticky_mem_spike_out[59];
	mem_spike_out[60] = gensticky_mem_spike_out[60];
	mem_spike_out[61] = gensticky_mem_spike_out[61];
	mem_spike_out[62] = gensticky_mem_spike_out[62];
	mem_spike_out[63] = gensticky_mem_spike_out[63];
	mem_spike_out[64] = gensticky_mem_spike_out[64];
	credit_spike_out[0] = gensticky_credit_spike_out[0];
	credit_spike_out[1] = gensticky_credit_spike_out[1];
	credit_spike_out[2] = gensticky_credit_spike_out[2];
	wr_credit_spike_out = gensticky_wr_credit_spike_out;
	wptr_spike_out = gensticky_wptr_spike_out;
	rptr_spike_out = gensticky_rptr_spike_out;
	empty_r_spike_out = gensticky_empty_r_spike_out;
	full_spike_out = gensticky_full_spike_out;
	rptr_n_spike_out = gensticky_rptr_n_spike_out;
	full_n_spike_out = gensticky_full_n_spike_out;
	empty_n_spike_out = gensticky_empty_n_spike_out;
	wptr_n_spike_out = gensticky_wptr_n_spike_out;
	rd_data_Vmemb = gensticky_rd_data_Vmemb;
	mem_Vmemb[0] = gensticky_mem_Vmemb[0];
	mem_Vmemb[1] = gensticky_mem_Vmemb[1];
	mem_Vmemb[2] = gensticky_mem_Vmemb[2];
	mem_Vmemb[3] = gensticky_mem_Vmemb[3];
	mem_Vmemb[4] = gensticky_mem_Vmemb[4];
	mem_Vmemb[5] = gensticky_mem_Vmemb[5];
	mem_Vmemb[6] = gensticky_mem_Vmemb[6];
	mem_Vmemb[7] = gensticky_mem_Vmemb[7];
	mem_Vmemb[8] = gensticky_mem_Vmemb[8];
	dat_w_l1_r = gensticky_dat_w_l1_r;
	cfg_threshold_r = gensticky_cfg_threshold_r;
	cfg_leakage_r = gensticky_cfg_leakage_r;
	cfg_baseAddr_r = gensticky_cfg_baseAddr_r;
	cfg_postsynCount_r = gensticky_cfg_postsynCount_r;
	cfg_layerBase_r[0] = gensticky_cfg_layerBase_r[0];
	cfg_layerBase_r[1] = gensticky_cfg_layerBase_r[1];
	cfg_layerBase_r[2] = gensticky_cfg_layerBase_r[2];
	cfg_layerBase_r[3] = gensticky_cfg_layerBase_r[3];
	cfg_layerBase_r[4] = gensticky_cfg_layerBase_r[4];
	step_en_sel0 = gensticky_step_en_sel0;
	state_sel0 = gensticky_state_sel0;
	done_sel0 = gensticky_done_sel0;
	en_w_l1_r = gensticky_en_w_l1_r;
	busy_sel0 = gensticky_busy_sel0;
	prelatched_sel0 = gensticky_prelatched_sel0;
	postidx_sel0 = gensticky_postidx_sel0;
	state_n_sel0 = gensticky_state_n_sel0;
	adr_w_l1_r = gensticky_adr_w_l1_r;
	syn_st = gensticky_syn_st;
	syn_done = gensticky_syn_done;
	rd_spike_in = gensticky_rd_spike_in;
	start_sel0 = gensticky_start_sel0;
	syn_busy = gensticky_syn_busy;
	syn_stn = gensticky_syn_stn;
	syn_pre = gensticky_syn_pre;
	preidx_sel0 = gensticky_preidx_sel0;
	rd_idx_Vmemb = gensticky_rd_idx_Vmemb;
	wr_idx_Vmemb = gensticky_wr_idx_Vmemb;
	wr_data_Vmemb = gensticky_wr_data_Vmemb;
	we_Vmemb = gensticky_we_Vmemb;
	neur_st = gensticky_neur_st;
	neur_done = gensticky_neur_done;
	neur_busy = gensticky_neur_busy;
	neur_idx = gensticky_neur_idx;
	neur_stn = gensticky_neur_stn;
	emit_st = gensticky_emit_st;
	emit_done = gensticky_emit_done;
	emit_fired = gensticky_emit_fired;
	we_spike_out = gensticky_we_spike_out;
	emit_busy = gensticky_emit_busy;
	emit_idx = gensticky_emit_idx;
	emit_stn = gensticky_emit_stn;
	wr_data_spike_out = gensticky_wr_data_spike_out;
	reg_en_core = gensticky_reg_en_core;
	core_state = gensticky_core_state;
	core_neur_start = gensticky_core_neur_start;
	core_emit_start = gensticky_core_emit_start;
	core_syn_gate = gensticky_core_syn_gate;
	neur_start = gensticky_neur_start;
	emit_start = gensticky_emit_start;
	core_stateN = gensticky_core_stateN;
	syn_gate_stub = gensticky_syn_gate_stub;
	// Buffering globals
	// Processing dlychains
	// fifo_in buffering
	// subproc fifo_in buffering
	// Payload logic
	tick = 32'd0;
	gen181_cyclix_genvar = (tg0_counter == tg0_last);
	gen182_cyclix_genvar = gen181_cyclix_genvar;
	gen0_rtl_var = gen182_cyclix_genvar;
	if (gen0_rtl_var)
		begin
		tick = 32'd1;
		tg0_counter = 32'd0;
		end
	gen183_cyclix_genvar = 1'd0;
	gen183_cyclix_genvar = (gen183_cyclix_genvar || gen182_cyclix_genvar);
	gen183_cyclix_genvar = !gen183_cyclix_genvar;
	gen1_rtl_var = gen183_cyclix_genvar;
	if (gen1_rtl_var)
		begin
		gen184_cyclix_genvar = (tg0_counter + 32'd1);
		tg0_next = gen184_cyclix_genvar;
		tg0_counter = tg0_next;
		end
	full_spike_in = full_r_spike_in;
	gen185_cyclix_genvar = (tick == 32'd1);
	gen186_cyclix_genvar = gen185_cyclix_genvar;
	gen2_rtl_var = gen186_cyclix_genvar;
	if (gen2_rtl_var)
		begin
		gen187_cyclix_genvar = ~act_spike_in;
		act_spike_in = gen187_cyclix_genvar;
		end
	gen188_cyclix_genvar = ~full_r_spike_in;
	gen189_cyclix_genvar = (wr_spike_in && gen188_cyclix_genvar);
	wr_en_spike_in = gen189_cyclix_genvar;
	gen190_cyclix_genvar = (wr_en_spike_in == 32'd1);
	gen191_cyclix_genvar = gen190_cyclix_genvar;
	gen3_rtl_var = gen191_cyclix_genvar;
	if (gen3_rtl_var)
		begin
		mem_spike_in[wptr_spike_in] = wr_data_spike_in;
		gen192_cyclix_genvar = (credit_spike_in[act_spike_in] + 32'd1);
		credit_spike_in[act_spike_in] = gen192_cyclix_genvar;
		end
	wr_credit_spike_in = credit_spike_in[act_spike_in];
	gen193_cyclix_genvar = ~act_spike_in;
	rd_credit_spike_in = credit_spike_in[gen193_cyclix_genvar];
	rd_data_spike_in = mem_spike_in[rptr_spike_in];
	wptr_spike_in = wptr_n_spike_in;
	rptr_spike_in = rptr_n_spike_in;
	empty_spike_in = empty_n_spike_in;
	full_r_spike_in = full_n_spike_in;
	gen194_cyclix_genvar = {wr_spike_in, rd_spike_in};
	case (gen194_cyclix_genvar)
		32'd1:
			begin
			gen195_cyclix_genvar = ~empty_spike_in;
			gen196_cyclix_genvar = gen195_cyclix_genvar;
			gen4_rtl_var = gen196_cyclix_genvar;
			if (gen4_rtl_var)
				begin
				gen197_cyclix_genvar = (rptr_spike_in + 32'd1);
				rptr_n_spike_in = gen197_cyclix_genvar;
				full_n_spike_in = 32'd0;
				gen198_cyclix_genvar = (rd_credit_spike_in > 32'd0);
				gen199_cyclix_genvar = gen198_cyclix_genvar;
				gen5_rtl_var = gen199_cyclix_genvar;
				if (gen5_rtl_var)
					begin
					gen200_cyclix_genvar = ~act_spike_in;
					gen201_cyclix_genvar = ~act_spike_in;
					gen202_cyclix_genvar = (credit_spike_in[gen201_cyclix_genvar] - 32'd1);
					credit_spike_in[gen200_cyclix_genvar] = gen202_cyclix_genvar;
					end
				gen203_cyclix_genvar = 1'd0;
				gen203_cyclix_genvar = (gen203_cyclix_genvar || gen199_cyclix_genvar);
				gen203_cyclix_genvar = !gen203_cyclix_genvar;
				gen6_rtl_var = gen203_cyclix_genvar;
				if (gen6_rtl_var)
					begin
					gen204_cyclix_genvar = ~act_spike_in;
					credit_spike_in[gen204_cyclix_genvar] = 32'd0;
					end
				gen205_cyclix_genvar = (rptr_spike_in + 32'd1);
				gen206_cyclix_genvar = (gen205_cyclix_genvar == wptr_spike_in);
				gen207_cyclix_genvar = gen206_cyclix_genvar;
				gen7_rtl_var = gen207_cyclix_genvar;
				if (gen7_rtl_var)
					begin
					empty_n_spike_in = 32'd1;
					end
				end
			gen208_cyclix_genvar = 1'd0;
			gen208_cyclix_genvar = (gen208_cyclix_genvar || gen196_cyclix_genvar);
			gen208_cyclix_genvar = !gen208_cyclix_genvar;
			gen8_rtl_var = gen208_cyclix_genvar;
			if (gen8_rtl_var)
				begin
				gen209_cyclix_genvar = ~act_spike_in;
				credit_spike_in[gen209_cyclix_genvar] = 32'd0;
				end
			end
		32'd2:
			begin
			gen210_cyclix_genvar = ~full_r_spike_in;
			gen211_cyclix_genvar = gen210_cyclix_genvar;
			gen9_rtl_var = gen211_cyclix_genvar;
			if (gen9_rtl_var)
				begin
				gen212_cyclix_genvar = (wptr_spike_in + 32'd1);
				wptr_n_spike_in = gen212_cyclix_genvar;
				empty_n_spike_in = 32'd0;
				gen213_cyclix_genvar = (wptr_spike_in + 32'd1);
				gen214_cyclix_genvar = (gen213_cyclix_genvar == rptr_spike_in);
				gen215_cyclix_genvar = gen214_cyclix_genvar;
				gen10_rtl_var = gen215_cyclix_genvar;
				if (gen10_rtl_var)
					begin
					full_n_spike_in = 32'd1;
					end
				end
			end
		32'd3:
			begin
			gen216_cyclix_genvar = (wptr_spike_in + 32'd1);
			wptr_n_spike_in = gen216_cyclix_genvar;
			gen217_cyclix_genvar = (rptr_spike_in + 32'd1);
			rptr_n_spike_in = gen217_cyclix_genvar;
			gen218_cyclix_genvar = (rd_credit_spike_in > 32'd0);
			gen219_cyclix_genvar = gen218_cyclix_genvar;
			gen11_rtl_var = gen219_cyclix_genvar;
			if (gen11_rtl_var)
				begin
				gen220_cyclix_genvar = ~act_spike_in;
				gen221_cyclix_genvar = ~act_spike_in;
				gen222_cyclix_genvar = (credit_spike_in[gen221_cyclix_genvar] - 32'd1);
				credit_spike_in[gen220_cyclix_genvar] = gen222_cyclix_genvar;
				end
			gen223_cyclix_genvar = 1'd0;
			gen223_cyclix_genvar = (gen223_cyclix_genvar || gen219_cyclix_genvar);
			gen223_cyclix_genvar = !gen223_cyclix_genvar;
			gen12_rtl_var = gen223_cyclix_genvar;
			if (gen12_rtl_var)
				begin
				gen224_cyclix_genvar = ~act_spike_in;
				credit_spike_in[gen224_cyclix_genvar] = 32'd0;
				end
			end
	endcase
	empty_spike_out = empty_r_spike_out;
	gen225_cyclix_genvar = (tick == 32'd1);
	gen226_cyclix_genvar = gen225_cyclix_genvar;
	gen13_rtl_var = gen226_cyclix_genvar;
	if (gen13_rtl_var)
		begin
		gen227_cyclix_genvar = ~act_spike_out;
		act_spike_out = gen227_cyclix_genvar;
		end
	gen228_cyclix_genvar = ~full_spike_out;
	gen229_cyclix_genvar = (we_spike_out && gen228_cyclix_genvar);
	wr_en_spike_out = gen229_cyclix_genvar;
	gen230_cyclix_genvar = (wr_en_spike_out == 32'd1);
	gen231_cyclix_genvar = gen230_cyclix_genvar;
	gen14_rtl_var = gen231_cyclix_genvar;
	if (gen14_rtl_var)
		begin
		mem_spike_out[wptr_spike_out] = wr_data_spike_out;
		gen232_cyclix_genvar = (credit_spike_out[act_spike_out] + 32'd1);
		credit_spike_out[act_spike_out] = gen232_cyclix_genvar;
		end
	wr_credit_spike_out = credit_spike_out[act_spike_out];
	gen233_cyclix_genvar = ~act_spike_out;
	rd_credit_spike_out = credit_spike_out[gen233_cyclix_genvar];
	rd_data_spike_out = mem_spike_out[rptr_spike_out];
	wptr_spike_out = wptr_n_spike_out;
	rptr_spike_out = rptr_n_spike_out;
	empty_r_spike_out = empty_n_spike_out;
	full_spike_out = full_n_spike_out;
	gen234_cyclix_genvar = {we_spike_out, rd_spike_out};
	case (gen234_cyclix_genvar)
		32'd1:
			begin
			gen235_cyclix_genvar = ~empty_r_spike_out;
			gen236_cyclix_genvar = gen235_cyclix_genvar;
			gen15_rtl_var = gen236_cyclix_genvar;
			if (gen15_rtl_var)
				begin
				gen237_cyclix_genvar = (rptr_spike_out + 32'd1);
				rptr_n_spike_out = gen237_cyclix_genvar;
				full_n_spike_out = 32'd0;
				gen238_cyclix_genvar = ~act_spike_out;
				gen239_cyclix_genvar = (rd_credit_spike_out > 32'd0);
				gen240_cyclix_genvar = gen239_cyclix_genvar;
				gen16_rtl_var = gen240_cyclix_genvar;
				if (gen16_rtl_var)
					begin
					gen241_cyclix_genvar = (credit_spike_out[gen238_cyclix_genvar] - 32'd1);
					credit_spike_out[gen238_cyclix_genvar] = gen241_cyclix_genvar;
					end
				gen242_cyclix_genvar = 1'd0;
				gen242_cyclix_genvar = (gen242_cyclix_genvar || gen240_cyclix_genvar);
				gen242_cyclix_genvar = !gen242_cyclix_genvar;
				gen17_rtl_var = gen242_cyclix_genvar;
				if (gen17_rtl_var)
					begin
					credit_spike_out[gen238_cyclix_genvar] = 32'd0;
					end
				gen243_cyclix_genvar = (rptr_spike_out + 32'd1);
				gen244_cyclix_genvar = (gen243_cyclix_genvar == wptr_spike_out);
				gen245_cyclix_genvar = gen244_cyclix_genvar;
				gen18_rtl_var = gen245_cyclix_genvar;
				if (gen18_rtl_var)
					begin
					empty_n_spike_out = 32'd1;
					end
				end
			gen246_cyclix_genvar = 1'd0;
			gen246_cyclix_genvar = (gen246_cyclix_genvar || gen236_cyclix_genvar);
			gen246_cyclix_genvar = !gen246_cyclix_genvar;
			gen19_rtl_var = gen246_cyclix_genvar;
			if (gen19_rtl_var)
				begin
				gen247_cyclix_genvar = ~act_spike_out;
				credit_spike_out[gen247_cyclix_genvar] = 32'd0;
				end
			end
		32'd2:
			begin
			gen248_cyclix_genvar = ~full_spike_out;
			gen249_cyclix_genvar = gen248_cyclix_genvar;
			gen20_rtl_var = gen249_cyclix_genvar;
			if (gen20_rtl_var)
				begin
				gen250_cyclix_genvar = (wptr_spike_out + 32'd1);
				wptr_n_spike_out = gen250_cyclix_genvar;
				empty_n_spike_out = 32'd0;
				gen251_cyclix_genvar = (wptr_spike_out + 32'd1);
				gen252_cyclix_genvar = (gen251_cyclix_genvar == rptr_spike_out);
				gen253_cyclix_genvar = gen252_cyclix_genvar;
				gen21_rtl_var = gen253_cyclix_genvar;
				if (gen21_rtl_var)
					begin
					full_n_spike_out = 32'd1;
					end
				end
			end
		32'd3:
			begin
			gen254_cyclix_genvar = (wptr_spike_out + 32'd1);
			wptr_n_spike_out = gen254_cyclix_genvar;
			gen255_cyclix_genvar = (rptr_spike_out + 32'd1);
			rptr_n_spike_out = gen255_cyclix_genvar;
			gen256_cyclix_genvar = ~act_spike_out;
			gen257_cyclix_genvar = (rd_credit_spike_out > 32'd0);
			gen258_cyclix_genvar = gen257_cyclix_genvar;
			gen22_rtl_var = gen258_cyclix_genvar;
			if (gen22_rtl_var)
				begin
				gen259_cyclix_genvar = (credit_spike_out[gen256_cyclix_genvar] - 32'd1);
				credit_spike_out[gen256_cyclix_genvar] = gen259_cyclix_genvar;
				end
			gen260_cyclix_genvar = 1'd0;
			gen260_cyclix_genvar = (gen260_cyclix_genvar || gen258_cyclix_genvar);
			gen260_cyclix_genvar = !gen260_cyclix_genvar;
			gen23_rtl_var = gen260_cyclix_genvar;
			if (gen23_rtl_var)
				begin
				credit_spike_out[gen256_cyclix_genvar] = 32'd0;
				end
			end
	endcase
	rd_data_Vmemb = mem_Vmemb[rd_idx_Vmemb];
	gen261_cyclix_genvar = (we_Vmemb == 32'd1);
	gen262_cyclix_genvar = gen261_cyclix_genvar;
	gen24_rtl_var = gen262_cyclix_genvar;
	if (gen24_rtl_var)
		begin
		mem_Vmemb[wr_idx_Vmemb] = wr_data_Vmemb;
		end
	dat_w_l1_r = dat_w_l1;
	adr_w_l1 = adr_w_l1_r;
	en_w_l1 = en_w_l1_r;
	cfg_threshold_r = cfg_threshold_i;
	cfg_leakage_r = cfg_leakage_i;
	cfg_baseAddr_r = cfg_baseAddr_i;
	cfg_postsynCount_r = cfg_postsynCount_i;
	cfg_layerBase_r[0] = cfg_layerBase_i[0];
	cfg_layerBase_r[1] = cfg_layerBase_i[1];
	cfg_layerBase_r[2] = cfg_layerBase_i[2];
	cfg_layerBase_r[3] = cfg_layerBase_i[3];
	cfg_layerBase_r[4] = cfg_layerBase_i[4];
	step_en_sel0 = 32'd1;
	state_sel0 = state_n_sel0;
	done_sel0 = 32'd0;
	en_w_l1_r = 32'd0;
	gen263_cyclix_genvar = (step_en_sel0 && busy_sel0);
	gen264_cyclix_genvar = (state_sel0 == 32'd0);
	gen265_cyclix_genvar = gen264_cyclix_genvar;
	gen25_rtl_var = gen265_cyclix_genvar;
	if (gen25_rtl_var)
		begin
		busy_sel0 = 32'd0;
		gen266_cyclix_genvar = (start_sel0 == 32'd1);
		gen267_cyclix_genvar = gen266_cyclix_genvar;
		gen26_rtl_var = gen267_cyclix_genvar;
		if (gen26_rtl_var)
			begin
			prelatched_sel0 = preidx_sel0;
			postidx_sel0 = 32'd0;
			busy_sel0 = 32'd1;
			state_n_sel0 = 32'd1;
			end
		end
	gen268_cyclix_genvar = (state_sel0 == 32'd1);
	gen269_cyclix_genvar = gen268_cyclix_genvar;
	gen27_rtl_var = gen269_cyclix_genvar;
	if (gen27_rtl_var)
		begin
		busy_sel0 = 32'd1;
		gen270_cyclix_genvar = (prelatched_sel0 * cfg_postsynCount_r);
		gen271_cyclix_genvar = (gen270_cyclix_genvar + postidx_sel0);
		gen272_cyclix_genvar = (gen271_cyclix_genvar + cfg_baseAddr_r);
		adr_w_l1_r = gen272_cyclix_genvar;
		en_w_l1_r = 32'd1;
		gen273_cyclix_genvar = (gen263_cyclix_genvar == 32'd1);
		gen274_cyclix_genvar = gen273_cyclix_genvar;
		gen28_rtl_var = gen274_cyclix_genvar;
		if (gen28_rtl_var)
			begin
			gen275_cyclix_genvar = (cfg_postsynCount_r - 32'd1);
			gen276_cyclix_genvar = (postidx_sel0 == gen275_cyclix_genvar);
			gen277_cyclix_genvar = gen276_cyclix_genvar;
			gen29_rtl_var = gen277_cyclix_genvar;
			if (gen29_rtl_var)
				begin
				done_sel0 = 32'd1;
				busy_sel0 = 32'd0;
				state_n_sel0 = 32'd0;
				end
			gen278_cyclix_genvar = 1'd0;
			gen278_cyclix_genvar = (gen278_cyclix_genvar || gen277_cyclix_genvar);
			gen278_cyclix_genvar = !gen278_cyclix_genvar;
			gen30_rtl_var = gen278_cyclix_genvar;
			if (gen30_rtl_var)
				begin
				gen279_cyclix_genvar = (postidx_sel0 + 32'd1);
				postidx_sel0 = gen279_cyclix_genvar;
				end
			end
		end
	syn_st = syn_stn;
	syn_done = 32'd0;
	rd_spike_in = 32'd0;
	start_sel0 = 32'd0;
	gen280_cyclix_genvar = (empty_spike_in == 32'd0);
	gen281_cyclix_genvar = (syn_gate_stub == 32'd1);
	gen282_cyclix_genvar = (gen281_cyclix_genvar && gen280_cyclix_genvar);
	gen283_cyclix_genvar = (syn_st == 32'd0);
	gen284_cyclix_genvar = gen283_cyclix_genvar;
	gen31_rtl_var = gen284_cyclix_genvar;
	if (gen31_rtl_var)
		begin
		syn_busy = 32'd0;
		gen285_cyclix_genvar = (gen282_cyclix_genvar == 32'd1);
		gen286_cyclix_genvar = gen285_cyclix_genvar;
		gen32_rtl_var = gen286_cyclix_genvar;
		if (gen32_rtl_var)
			begin
			rd_spike_in = 32'd1;
			syn_stn = 32'd1;
			end
		gen287_cyclix_genvar = 1'd0;
		gen287_cyclix_genvar = (gen287_cyclix_genvar || gen286_cyclix_genvar);
		gen287_cyclix_genvar = !gen287_cyclix_genvar;
		gen33_rtl_var = gen287_cyclix_genvar;
		if (gen33_rtl_var)
			begin
			syn_done = 32'd1;
			end
		end
	gen288_cyclix_genvar = (syn_st == 32'd1);
	gen289_cyclix_genvar = gen288_cyclix_genvar;
	gen34_rtl_var = gen289_cyclix_genvar;
	if (gen34_rtl_var)
		begin
		syn_busy = 32'd1;
		rd_spike_in = 32'd0;
		syn_pre = rd_data_spike_in;
		preidx_sel0 = rd_data_spike_in;
		start_sel0 = 32'd1;
		syn_stn = 32'd2;
		end
	gen290_cyclix_genvar = (syn_st == 32'd2);
	gen291_cyclix_genvar = gen290_cyclix_genvar;
	gen35_rtl_var = gen291_cyclix_genvar;
	if (gen35_rtl_var)
		begin
		syn_busy = 32'd1;
		start_sel0 = 32'd0;
		syn_stn = 32'd3;
		end
	gen292_cyclix_genvar = (syn_st == 32'd3);
	gen293_cyclix_genvar = gen292_cyclix_genvar;
	gen36_rtl_var = gen293_cyclix_genvar;
	if (gen36_rtl_var)
		begin
		syn_busy = 32'd1;
		rd_idx_Vmemb = postidx_sel0;
		gen294_cyclix_genvar = (rd_data_Vmemb + dat_w_l1_r);
		wr_idx_Vmemb = postidx_sel0;
		wr_data_Vmemb = gen294_cyclix_genvar;
		we_Vmemb = 32'd1;
		gen295_cyclix_genvar = (done_sel0 == 32'd1);
		gen296_cyclix_genvar = gen295_cyclix_genvar;
		gen37_rtl_var = gen296_cyclix_genvar;
		if (gen37_rtl_var)
			begin
			we_Vmemb = 32'd0;
			syn_stn = 32'd0;
			end
		end
	neur_st = neur_stn;
	neur_done = 32'd0;
	we_Vmemb = 32'd0;
	gen297_cyclix_genvar = (neur_st == 32'd0);
	gen298_cyclix_genvar = gen297_cyclix_genvar;
	gen38_rtl_var = gen298_cyclix_genvar;
	if (gen38_rtl_var)
		begin
		neur_busy = 32'd0;
		gen299_cyclix_genvar = (neur_start == 32'd1);
		gen300_cyclix_genvar = gen299_cyclix_genvar;
		gen39_rtl_var = gen300_cyclix_genvar;
		if (gen39_rtl_var)
			begin
			neur_idx = 32'd0;
			neur_busy = 32'd1;
			neur_stn = 32'd1;
			end
		end
	gen301_cyclix_genvar = (neur_st == 32'd1);
	gen302_cyclix_genvar = gen301_cyclix_genvar;
	gen40_rtl_var = gen302_cyclix_genvar;
	if (gen40_rtl_var)
		begin
		neur_busy = 32'd1;
		rd_idx_Vmemb = neur_idx;
		neur_stn = 32'd2;
		end
	gen303_cyclix_genvar = (neur_st == 32'd2);
	gen304_cyclix_genvar = gen303_cyclix_genvar;
	gen41_rtl_var = gen304_cyclix_genvar;
	if (gen41_rtl_var)
		begin
		neur_busy = 32'd1;
		neur_acc = rd_data_Vmemb;
		gen305_cyclix_genvar = (neur_acc - cfg_leakage_r);
		neur_acc = gen305_cyclix_genvar;
		gen306_cyclix_genvar = (neur_acc >> cfg_threshold_r);
		neur_acc = gen306_cyclix_genvar;
		wr_idx_Vmemb = neur_idx;
		wr_data_Vmemb = neur_acc;
		we_Vmemb = 32'd1;
		gen307_cyclix_genvar = (cfg_postsynCount_r - 32'd1);
		gen308_cyclix_genvar = (neur_idx == gen307_cyclix_genvar);
		gen309_cyclix_genvar = gen308_cyclix_genvar;
		gen42_rtl_var = gen309_cyclix_genvar;
		if (gen42_rtl_var)
			begin
			we_Vmemb = 32'd0;
			neur_done = 32'd1;
			neur_busy = 32'd0;
			neur_stn = 32'd0;
			end
		gen310_cyclix_genvar = 1'd0;
		gen310_cyclix_genvar = (gen310_cyclix_genvar || gen309_cyclix_genvar);
		gen310_cyclix_genvar = !gen310_cyclix_genvar;
		gen43_rtl_var = gen310_cyclix_genvar;
		if (gen43_rtl_var)
			begin
			we_Vmemb = 32'd0;
			gen311_cyclix_genvar = (neur_idx + 32'd1);
			neur_idx = gen311_cyclix_genvar;
			neur_stn = 32'd1;
			end
		end
	emit_st = emit_stn;
	emit_done = 32'd0;
	emit_fired = 32'd0;
	we_spike_out = 32'd0;
	we_Vmemb = 32'd0;
	gen312_cyclix_genvar = (emit_st == 32'd0);
	gen313_cyclix_genvar = gen312_cyclix_genvar;
	gen44_rtl_var = gen313_cyclix_genvar;
	if (gen44_rtl_var)
		begin
		emit_busy = 32'd0;
		gen314_cyclix_genvar = (emit_start == 32'd1);
		gen315_cyclix_genvar = gen314_cyclix_genvar;
		gen45_rtl_var = gen315_cyclix_genvar;
		if (gen45_rtl_var)
			begin
			emit_idx = 32'd0;
			emit_busy = 32'd1;
			emit_stn = 32'd1;
			end
		end
	gen316_cyclix_genvar = (emit_st == 32'd1);
	gen317_cyclix_genvar = gen316_cyclix_genvar;
	gen46_rtl_var = gen317_cyclix_genvar;
	if (gen46_rtl_var)
		begin
		emit_busy = 32'd1;
		rd_idx_Vmemb = emit_idx;
		emit_stn = 32'd2;
		end
	gen318_cyclix_genvar = (emit_st == 32'd2);
	gen319_cyclix_genvar = gen318_cyclix_genvar;
	gen47_rtl_var = gen319_cyclix_genvar;
	if (gen47_rtl_var)
		begin
		emit_busy = 32'd1;
		gen320_cyclix_genvar = (rd_data_Vmemb > cfg_threshold_r);
		gen321_cyclix_genvar = (rd_data_Vmemb == cfg_threshold_r);
		gen322_cyclix_genvar = (gen320_cyclix_genvar >= gen321_cyclix_genvar);
		gen323_cyclix_genvar = ~full_spike_out;
		gen324_cyclix_genvar = (gen322_cyclix_genvar && gen323_cyclix_genvar);
		gen325_cyclix_genvar = (gen324_cyclix_genvar == 32'd1);
		gen326_cyclix_genvar = gen325_cyclix_genvar;
		gen48_rtl_var = gen326_cyclix_genvar;
		if (gen48_rtl_var)
			begin
			we_spike_out = 32'd1;
			wr_data_spike_out = emit_idx;
			emit_fired = 32'd1;
			wr_idx_Vmemb = emit_idx;
			wr_data_Vmemb = cfg_leakage_r;
			we_Vmemb = 32'd1;
			end
		gen327_cyclix_genvar = (gen322_cyclix_genvar && full_spike_out);
		gen328_cyclix_genvar = (gen327_cyclix_genvar == 32'd1);
		gen329_cyclix_genvar = gen328_cyclix_genvar;
		gen49_rtl_var = gen329_cyclix_genvar;
		if (gen49_rtl_var)
			begin
			emit_stn = 32'd2;
			end
		gen330_cyclix_genvar = ~gen327_cyclix_genvar;
		gen331_cyclix_genvar = (gen330_cyclix_genvar == 32'd1);
		gen332_cyclix_genvar = gen331_cyclix_genvar;
		gen50_rtl_var = gen332_cyclix_genvar;
		if (gen50_rtl_var)
			begin
			gen333_cyclix_genvar = (cfg_postsynCount_r - 32'd1);
			gen334_cyclix_genvar = (emit_idx == gen333_cyclix_genvar);
			gen335_cyclix_genvar = gen334_cyclix_genvar;
			gen51_rtl_var = gen335_cyclix_genvar;
			if (gen51_rtl_var)
				begin
				emit_done = 32'd1;
				emit_busy = 32'd0;
				emit_stn = 32'd0;
				end
			gen336_cyclix_genvar = 1'd0;
			gen336_cyclix_genvar = (gen336_cyclix_genvar || gen335_cyclix_genvar);
			gen336_cyclix_genvar = !gen336_cyclix_genvar;
			gen52_rtl_var = gen336_cyclix_genvar;
			if (gen52_rtl_var)
				begin
				gen337_cyclix_genvar = (emit_idx + 32'd1);
				emit_idx = gen337_cyclix_genvar;
				emit_stn = 32'd1;
				end
			end
		end
	reg_en_core = en_core;
	core_state = core_stateN;
	core_neur_start = 32'd0;
	core_emit_start = 32'd0;
	core_syn_gate = 32'd0;
	neur_start = core_neur_start;
	emit_start = core_emit_start;
	gen338_cyclix_genvar = (core_state == 32'd0);
	gen339_cyclix_genvar = gen338_cyclix_genvar;
	gen53_rtl_var = gen339_cyclix_genvar;
	if (gen53_rtl_var)
		begin
		gen340_cyclix_genvar = (reg_en_core == 32'd1);
		gen341_cyclix_genvar = gen340_cyclix_genvar;
		gen54_rtl_var = gen341_cyclix_genvar;
		if (gen54_rtl_var)
			begin
			core_stateN = 32'd1;
			end
		end
	gen342_cyclix_genvar = (core_state == 32'd1);
	gen343_cyclix_genvar = gen342_cyclix_genvar;
	gen55_rtl_var = gen343_cyclix_genvar;
	if (gen55_rtl_var)
		begin
		gen344_cyclix_genvar = (tick == 32'd1);
		gen345_cyclix_genvar = gen344_cyclix_genvar;
		gen56_rtl_var = gen345_cyclix_genvar;
		if (gen56_rtl_var)
			begin
			core_syn_gate = 32'd1;
			core_stateN = 32'd2;
			end
		end
	gen346_cyclix_genvar = (core_state == 32'd2);
	gen347_cyclix_genvar = gen346_cyclix_genvar;
	gen57_rtl_var = gen347_cyclix_genvar;
	if (gen57_rtl_var)
		begin
		gen348_cyclix_genvar = (syn_done == 32'd1);
		gen349_cyclix_genvar = gen348_cyclix_genvar;
		gen58_rtl_var = gen349_cyclix_genvar;
		if (gen58_rtl_var)
			begin
			core_stateN = 32'd3;
			end
		end
	gen350_cyclix_genvar = (core_state == 32'd3);
	gen351_cyclix_genvar = gen350_cyclix_genvar;
	gen59_rtl_var = gen351_cyclix_genvar;
	if (gen59_rtl_var)
		begin
		gen352_cyclix_genvar = (tick == 32'd1);
		gen353_cyclix_genvar = gen352_cyclix_genvar;
		gen60_rtl_var = gen353_cyclix_genvar;
		if (gen60_rtl_var)
			begin
			core_neur_start = 32'd1;
			core_stateN = 32'd4;
			end
		end
	gen354_cyclix_genvar = (core_state == 32'd4);
	gen355_cyclix_genvar = gen354_cyclix_genvar;
	gen61_rtl_var = gen355_cyclix_genvar;
	if (gen61_rtl_var)
		begin
		gen356_cyclix_genvar = (neur_done == 32'd1);
		gen357_cyclix_genvar = gen356_cyclix_genvar;
		gen62_rtl_var = gen357_cyclix_genvar;
		if (gen62_rtl_var)
			begin
			core_emit_start = 32'd1;
			core_stateN = 32'd5;
			end
		end
	gen358_cyclix_genvar = (core_state == 32'd5);
	gen359_cyclix_genvar = gen358_cyclix_genvar;
	gen63_rtl_var = gen359_cyclix_genvar;
	if (gen63_rtl_var)
		begin
		gen360_cyclix_genvar = (emit_done == 32'd1);
		gen361_cyclix_genvar = gen360_cyclix_genvar;
		gen64_rtl_var = gen361_cyclix_genvar;
		if (gen64_rtl_var)
			begin
			core_stateN = 32'd1;
			end
		end
	syn_gate_stub = core_syn_gate;
	end


endmodule
