// ===========================================================
// RTL generated by ActiveCore framework
// Date: 2025-03-10 23:31:22
// Copyright Alexander Antonov <antonov.alex.alex@gmail.com>
// ===========================================================

`ifndef __n_core_h_
`define __n_core_h_

`endif // __n_core_h_
