// ===========================================================
// RTL generated by ActiveCore framework
// Date: 2024-07-19 16:26:19
// Copyright Alexander Antonov <antonov.alex.alex@gmail.com>
// ===========================================================

`include "Neuromorphic_design.svh"

module Neuromorphic_design (
	input logic unsigned [0:0] clk_i
	, input logic unsigned [0:0] rst_i
	, input logic unsigned [0:0] input_buf_wr_en
	, input logic unsigned [0:0] input_buf_data_in
	, input logic unsigned [1:0] input_buf_read_addr
	, input logic unsigned [0:0] input_buf_rd_en
	, output logic unsigned [0:0] input_buf_data_out
	, input logic unsigned [0:0] output_buf_wr_en
	, input logic unsigned [0:0] output_buf_data_in
	, input logic unsigned [1:0] output_buf_read_addr
	, input logic unsigned [0:0] output_buf_rd_en
	, output logic unsigned [0:0] output_buf_data_out
	, output logic unsigned [0:0] dbg_tick
	, output logic unsigned [31:0] dbg_clk_counter
	, output logic unsigned [31:0] dbg_tick_period
	, output logic unsigned [31:0] dbg_presyn_neuron_counter_num
	, output logic unsigned [31:0] dbg_postsyn_neuron_counter_num
	, input logic unsigned [0:0] weight_memory_wr_en
	, input logic unsigned [1:0] weight_memory_data_in
	, input logic unsigned [1:0] weight_memory_read_addr
	, input logic unsigned [0:0] weight_memory_rd_en
	, output logic unsigned [1:0] weight_memory_data_out
	, input logic unsigned [2:0] cntl_sig
);


logic unsigned [1:0] input_buf_wr_ptr;
logic unsigned [0:0] reg_input_buf_wr_en;
logic unsigned [0:0] reg_input_buf_rd_en;
logic unsigned [0:0] input_buf_mem [4:0];
logic unsigned [1:0] output_buf_wr_ptr;
logic unsigned [0:0] reg_output_buf_wr_en;
logic unsigned [0:0] reg_output_buf_rd_en;
logic unsigned [0:0] output_buf_mem [4:0];
logic unsigned [31:0] tick;
logic unsigned [31:0] tick_period;
logic unsigned [31:0] clk_counter;
logic unsigned [31:0] next_clk_count;
logic unsigned [31:0] presyn_neuron_counter_num;
logic unsigned [31:0] next_neuron_num;
logic unsigned [31:0] postsyn_neuron_counter_num;
logic unsigned [31:0] next_postsyn_neuron_num;
logic unsigned [2:0] reg_cntl_counter_sig;
logic unsigned [2:0] weight_memory [3:0] [3:0];
logic unsigned [0:0] reg_weight_memory_wr_en;
logic unsigned [0:0] reg_weight_memory_rd_en;
logic unsigned [2:0] reg_cntl_sig;
logic unsigned [0:0] dynamic_mem [4:0];
logic unsigned [31:0] input_buf_counter_num;
logic unsigned [31:0] next_input_buf_counter_num;
logic unsigned [31:0] dynamic_mem_counter_num;
logic unsigned [31:0] next_dynamic_mem_counter_num;
logic unsigned [31:0] leakage;
logic unsigned [31:0] threshold;
logic unsigned [0:0] gen55_cyclix_genvar;
logic unsigned [0:0] gen56_cyclix_genvar;
logic unsigned [32:0] gen57_cyclix_genvar;
logic unsigned [0:0] gen58_cyclix_genvar;
logic unsigned [0:0] gen59_cyclix_genvar;
logic unsigned [0:0] gen60_cyclix_genvar;
logic unsigned [0:0] gen61_cyclix_genvar;
logic unsigned [32:0] gen62_cyclix_genvar;
logic unsigned [0:0] gen63_cyclix_genvar;
logic unsigned [0:0] gen64_cyclix_genvar;
logic unsigned [0:0] gen65_cyclix_genvar;
logic unsigned [0:0] gen66_cyclix_genvar;
logic unsigned [32:0] gen67_cyclix_genvar;
logic unsigned [0:0] gen68_cyclix_genvar;
logic unsigned [0:0] gen69_cyclix_genvar;
logic unsigned [0:0] gen70_cyclix_genvar;
logic unsigned [0:0] gen71_cyclix_genvar;
logic unsigned [0:0] gen72_cyclix_genvar;
logic unsigned [0:0] gen73_cyclix_genvar;
logic unsigned [0:0] gen74_cyclix_genvar;
logic unsigned [0:0] gen75_cyclix_genvar;
logic unsigned [0:0] gen76_cyclix_genvar;
logic unsigned [32:0] gen77_cyclix_genvar;
logic unsigned [0:0] gen78_cyclix_genvar;
logic unsigned [32:0] gen79_cyclix_genvar;
logic unsigned [0:0] gen80_cyclix_genvar;
logic unsigned [0:0] gen81_cyclix_genvar;
logic unsigned [0:0] gen82_cyclix_genvar;
logic unsigned [0:0] gen83_cyclix_genvar;
logic unsigned [0:0] gen84_cyclix_genvar;
logic unsigned [0:0] gen85_cyclix_genvar;
logic unsigned [0:0] gen86_cyclix_genvar;
logic unsigned [0:0] gen87_cyclix_genvar;
logic unsigned [0:0] gen88_cyclix_genvar;
logic unsigned [0:0] gen89_cyclix_genvar;
logic unsigned [0:0] gen90_cyclix_genvar;
logic unsigned [0:0] gen91_cyclix_genvar;
logic unsigned [0:0] gen92_cyclix_genvar;
logic unsigned [0:0] gen93_cyclix_genvar;
logic unsigned [0:0] gen94_cyclix_genvar;
logic unsigned [0:0] gen95_cyclix_genvar;
logic unsigned [0:0] gen96_cyclix_genvar;
logic unsigned [0:0] gen97_cyclix_genvar;
logic unsigned [32:0] gen98_cyclix_genvar;
logic unsigned [32:0] gen99_cyclix_genvar;
logic unsigned [0:0] gen100_cyclix_genvar;
logic unsigned [0:0] gen101_cyclix_genvar;
logic unsigned [0:0] gen102_cyclix_genvar;
logic unsigned [0:0] gen103_cyclix_genvar;
logic unsigned [0:0] gen104_cyclix_genvar;
logic unsigned [0:0] gen105_cyclix_genvar;
logic unsigned [32:0] gen106_cyclix_genvar;
logic unsigned [0:0] gen107_cyclix_genvar;
logic unsigned [0:0] gen108_cyclix_genvar;
logic unsigned [0:0] gen109_cyclix_genvar;
logic unsigned [0:0] gen0_rtl_var;
logic unsigned [0:0] gen1_rtl_var;
logic unsigned [0:0] gen2_rtl_var;
logic unsigned [0:0] gen3_rtl_var;
logic unsigned [0:0] gen4_rtl_var;
logic unsigned [0:0] gen5_rtl_var;
logic unsigned [0:0] gen6_rtl_var;
logic unsigned [0:0] gen7_rtl_var;
logic unsigned [0:0] gen8_rtl_var;
logic unsigned [0:0] gen9_rtl_var;
logic unsigned [0:0] gen10_rtl_var;
logic unsigned [0:0] gen11_rtl_var;
logic unsigned [0:0] gen12_rtl_var;
logic unsigned [0:0] gen13_rtl_var;
logic unsigned [0:0] gen14_rtl_var;
logic unsigned [0:0] gen15_rtl_var;
logic unsigned [0:0] gen16_rtl_var;
logic unsigned [0:0] gen17_rtl_var;
logic unsigned [0:0] gen18_rtl_var;
logic unsigned [0:0] gen19_rtl_var;
logic unsigned [0:0] gen20_rtl_var;
logic unsigned [0:0] gen21_rtl_var;
logic unsigned [0:0] gen22_rtl_var;
logic unsigned [0:0] gen23_rtl_var;
logic unsigned [0:0] gen24_rtl_var;
logic unsigned [0:0] gen25_rtl_var;

logic unsigned [1:0] gensticky_input_buf_wr_ptr;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_input_buf_wr_ptr <= 32'd0;
		end
	else
		begin
		gensticky_input_buf_wr_ptr <= input_buf_wr_ptr;
		end

logic unsigned [0:0] gensticky_reg_input_buf_wr_en;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_reg_input_buf_wr_en <= 32'd0;
		end
	else
		begin
		gensticky_reg_input_buf_wr_en <= reg_input_buf_wr_en;
		end

logic unsigned [0:0] gensticky_reg_input_buf_rd_en;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_reg_input_buf_rd_en <= 32'd0;
		end
	else
		begin
		gensticky_reg_input_buf_rd_en <= reg_input_buf_rd_en;
		end

logic unsigned [0:0] gensticky_input_buf_mem [4:0];
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_input_buf_mem[0] <= 32'd0;
		gensticky_input_buf_mem[1] <= 32'd0;
		gensticky_input_buf_mem[2] <= 32'd0;
		gensticky_input_buf_mem[3] <= 32'd0;
		gensticky_input_buf_mem[4] <= 32'd0;
		end
	else
		begin
		gensticky_input_buf_mem[0] <= input_buf_mem[0];
		gensticky_input_buf_mem[1] <= input_buf_mem[1];
		gensticky_input_buf_mem[2] <= input_buf_mem[2];
		gensticky_input_buf_mem[3] <= input_buf_mem[3];
		gensticky_input_buf_mem[4] <= input_buf_mem[4];
		end

logic unsigned [1:0] gensticky_output_buf_wr_ptr;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_output_buf_wr_ptr <= 32'd0;
		end
	else
		begin
		gensticky_output_buf_wr_ptr <= output_buf_wr_ptr;
		end

logic unsigned [0:0] gensticky_reg_output_buf_wr_en;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_reg_output_buf_wr_en <= 32'd0;
		end
	else
		begin
		gensticky_reg_output_buf_wr_en <= reg_output_buf_wr_en;
		end

logic unsigned [0:0] gensticky_reg_output_buf_rd_en;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_reg_output_buf_rd_en <= 32'd0;
		end
	else
		begin
		gensticky_reg_output_buf_rd_en <= reg_output_buf_rd_en;
		end

logic unsigned [0:0] gensticky_output_buf_mem [4:0];
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_output_buf_mem[0] <= 32'd0;
		gensticky_output_buf_mem[1] <= 32'd0;
		gensticky_output_buf_mem[2] <= 32'd0;
		gensticky_output_buf_mem[3] <= 32'd0;
		gensticky_output_buf_mem[4] <= 32'd0;
		end
	else
		begin
		gensticky_output_buf_mem[0] <= output_buf_mem[0];
		gensticky_output_buf_mem[1] <= output_buf_mem[1];
		gensticky_output_buf_mem[2] <= output_buf_mem[2];
		gensticky_output_buf_mem[3] <= output_buf_mem[3];
		gensticky_output_buf_mem[4] <= output_buf_mem[4];
		end

logic unsigned [31:0] gensticky_tick;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_tick <= 32'd0;
		end
	else
		begin
		gensticky_tick <= tick;
		end

logic unsigned [31:0] gensticky_tick_period;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_tick_period <= 32'd500;
		end
	else
		begin
		gensticky_tick_period <= tick_period;
		end

logic unsigned [31:0] gensticky_clk_counter;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_clk_counter <= 32'd0;
		end
	else
		begin
		gensticky_clk_counter <= clk_counter;
		end

logic unsigned [31:0] gensticky_next_clk_count;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_next_clk_count <= 32'd0;
		end
	else
		begin
		gensticky_next_clk_count <= next_clk_count;
		end

logic unsigned [31:0] gensticky_presyn_neuron_counter_num;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_presyn_neuron_counter_num <= 32'd0;
		end
	else
		begin
		gensticky_presyn_neuron_counter_num <= presyn_neuron_counter_num;
		end

logic unsigned [31:0] gensticky_next_neuron_num;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_next_neuron_num <= 32'd0;
		end
	else
		begin
		gensticky_next_neuron_num <= next_neuron_num;
		end

logic unsigned [31:0] gensticky_postsyn_neuron_counter_num;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_postsyn_neuron_counter_num <= 32'd0;
		end
	else
		begin
		gensticky_postsyn_neuron_counter_num <= postsyn_neuron_counter_num;
		end

logic unsigned [31:0] gensticky_next_postsyn_neuron_num;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_next_postsyn_neuron_num <= 32'd0;
		end
	else
		begin
		gensticky_next_postsyn_neuron_num <= next_postsyn_neuron_num;
		end

logic unsigned [2:0] gensticky_reg_cntl_counter_sig;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_reg_cntl_counter_sig <= 32'd0;
		end
	else
		begin
		gensticky_reg_cntl_counter_sig <= reg_cntl_counter_sig;
		end

logic unsigned [2:0] gensticky_weight_memory [3:0] [3:0];
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_weight_memory[0][0] <= 32'd0;
		gensticky_weight_memory[0][1] <= 32'd0;
		gensticky_weight_memory[0][2] <= 32'd0;
		gensticky_weight_memory[0][3] <= 32'd0;
		gensticky_weight_memory[1][0] <= 32'd0;
		gensticky_weight_memory[1][1] <= 32'd0;
		gensticky_weight_memory[1][2] <= 32'd0;
		gensticky_weight_memory[1][3] <= 32'd0;
		gensticky_weight_memory[2][0] <= 32'd0;
		gensticky_weight_memory[2][1] <= 32'd0;
		gensticky_weight_memory[2][2] <= 32'd0;
		gensticky_weight_memory[2][3] <= 32'd0;
		gensticky_weight_memory[3][0] <= 32'd0;
		gensticky_weight_memory[3][1] <= 32'd0;
		gensticky_weight_memory[3][2] <= 32'd0;
		gensticky_weight_memory[3][3] <= 32'd0;
		end
	else
		begin
		gensticky_weight_memory[0][0] <= weight_memory[0][0];
		gensticky_weight_memory[0][1] <= weight_memory[0][1];
		gensticky_weight_memory[0][2] <= weight_memory[0][2];
		gensticky_weight_memory[0][3] <= weight_memory[0][3];
		gensticky_weight_memory[1][0] <= weight_memory[1][0];
		gensticky_weight_memory[1][1] <= weight_memory[1][1];
		gensticky_weight_memory[1][2] <= weight_memory[1][2];
		gensticky_weight_memory[1][3] <= weight_memory[1][3];
		gensticky_weight_memory[2][0] <= weight_memory[2][0];
		gensticky_weight_memory[2][1] <= weight_memory[2][1];
		gensticky_weight_memory[2][2] <= weight_memory[2][2];
		gensticky_weight_memory[2][3] <= weight_memory[2][3];
		gensticky_weight_memory[3][0] <= weight_memory[3][0];
		gensticky_weight_memory[3][1] <= weight_memory[3][1];
		gensticky_weight_memory[3][2] <= weight_memory[3][2];
		gensticky_weight_memory[3][3] <= weight_memory[3][3];
		end

logic unsigned [0:0] gensticky_reg_weight_memory_wr_en;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_reg_weight_memory_wr_en <= 32'd0;
		end
	else
		begin
		gensticky_reg_weight_memory_wr_en <= reg_weight_memory_wr_en;
		end

logic unsigned [0:0] gensticky_reg_weight_memory_rd_en;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_reg_weight_memory_rd_en <= 32'd0;
		end
	else
		begin
		gensticky_reg_weight_memory_rd_en <= reg_weight_memory_rd_en;
		end

logic unsigned [2:0] gensticky_reg_cntl_sig;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_reg_cntl_sig <= 32'd0;
		end
	else
		begin
		gensticky_reg_cntl_sig <= reg_cntl_sig;
		end

logic unsigned [0:0] gensticky_dynamic_mem [4:0];
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_dynamic_mem[0] <= 32'd0;
		gensticky_dynamic_mem[1] <= 32'd0;
		gensticky_dynamic_mem[2] <= 32'd0;
		gensticky_dynamic_mem[3] <= 32'd0;
		gensticky_dynamic_mem[4] <= 32'd0;
		end
	else
		begin
		gensticky_dynamic_mem[0] <= dynamic_mem[0];
		gensticky_dynamic_mem[1] <= dynamic_mem[1];
		gensticky_dynamic_mem[2] <= dynamic_mem[2];
		gensticky_dynamic_mem[3] <= dynamic_mem[3];
		gensticky_dynamic_mem[4] <= dynamic_mem[4];
		end

logic unsigned [31:0] gensticky_input_buf_counter_num;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_input_buf_counter_num <= 32'd0;
		end
	else
		begin
		gensticky_input_buf_counter_num <= input_buf_counter_num;
		end

logic unsigned [31:0] gensticky_next_input_buf_counter_num;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_next_input_buf_counter_num <= 32'd0;
		end
	else
		begin
		gensticky_next_input_buf_counter_num <= next_input_buf_counter_num;
		end

logic unsigned [31:0] gensticky_dynamic_mem_counter_num;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_dynamic_mem_counter_num <= 32'd0;
		end
	else
		begin
		gensticky_dynamic_mem_counter_num <= dynamic_mem_counter_num;
		end

logic unsigned [31:0] gensticky_next_dynamic_mem_counter_num;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_next_dynamic_mem_counter_num <= 32'd0;
		end
	else
		begin
		gensticky_next_dynamic_mem_counter_num <= next_dynamic_mem_counter_num;
		end

logic unsigned [31:0] gensticky_leakage;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_leakage <= 32'd1;
		end
	else
		begin
		gensticky_leakage <= leakage;
		end

logic unsigned [31:0] gensticky_threshold;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_threshold <= 32'd2;
		end
	else
		begin
		gensticky_threshold <= threshold;
		end


always_comb
	begin
	input_buf_mem[0] = 32'd0;
	input_buf_mem[1] = 32'd0;
	input_buf_mem[2] = 32'd0;
	input_buf_mem[3] = 32'd0;
	input_buf_mem[4] = 32'd0;
	gen57_cyclix_genvar = 32'd0;
	input_buf_wr_ptr = 32'd0;
	input_buf_data_out = 32'd0;
	output_buf_mem[0] = 32'd0;
	output_buf_mem[1] = 32'd0;
	output_buf_mem[2] = 32'd0;
	output_buf_mem[3] = 32'd0;
	output_buf_mem[4] = 32'd0;
	gen62_cyclix_genvar = 32'd0;
	output_buf_wr_ptr = 32'd0;
	output_buf_data_out = 32'd0;
	tick = 32'd0;
	gen67_cyclix_genvar = 32'd0;
	next_clk_count = 32'd0;
	clk_counter = 32'd0;
	postsyn_neuron_counter_num = 32'd0;
	presyn_neuron_counter_num = 32'd0;
	gen77_cyclix_genvar = 32'd0;
	next_neuron_num = 32'd0;
	gen79_cyclix_genvar = 32'd0;
	next_postsyn_neuron_num = 32'd0;
	gen75_cyclix_genvar = 32'd0;
	gen76_cyclix_genvar = 32'd0;
	gen9_rtl_var = 32'd0;
	gen78_cyclix_genvar = 32'd0;
	gen10_rtl_var = 32'd0;
	gen73_cyclix_genvar = 32'd0;
	gen74_cyclix_genvar = 32'd0;
	gen8_rtl_var = 32'd0;
	reg_cntl_counter_sig = 32'd0;
	weight_memory[0][0] = 32'd0;
	weight_memory[0][1] = 32'd0;
	weight_memory[0][2] = 32'd0;
	weight_memory[0][3] = 32'd0;
	weight_memory[1][0] = 32'd0;
	weight_memory[1][1] = 32'd0;
	weight_memory[1][2] = 32'd0;
	weight_memory[1][3] = 32'd0;
	weight_memory[2][0] = 32'd0;
	weight_memory[2][1] = 32'd0;
	weight_memory[2][2] = 32'd0;
	weight_memory[2][3] = 32'd0;
	weight_memory[3][0] = 32'd0;
	weight_memory[3][1] = 32'd0;
	weight_memory[3][2] = 32'd0;
	weight_memory[3][3] = 32'd0;
	gen84_cyclix_genvar = 32'd0;
	gen85_cyclix_genvar = 32'd0;
	gen13_rtl_var = 32'd0;
	weight_memory_data_out = 32'd0;
	gen88_cyclix_genvar = 32'd0;
	gen89_cyclix_genvar = 32'd0;
	gen15_rtl_var = 32'd0;
	dynamic_mem[0] = 32'd0;
	dynamic_mem[1] = 32'd0;
	dynamic_mem[2] = 32'd0;
	dynamic_mem[3] = 32'd0;
	dynamic_mem[4] = 32'd0;
	gen96_cyclix_genvar = 32'd0;
	gen97_cyclix_genvar = 32'd0;
	gen19_rtl_var = 32'd0;
	gen98_cyclix_genvar = 32'd0;
	next_input_buf_counter_num = 32'd0;
	input_buf_counter_num = 32'd0;
	gen94_cyclix_genvar = 32'd0;
	gen95_cyclix_genvar = 32'd0;
	gen18_rtl_var = 32'd0;
	gen99_cyclix_genvar = 32'd0;
	next_dynamic_mem_counter_num = 32'd0;
	dynamic_mem_counter_num = 32'd0;
	gen106_cyclix_genvar = 32'd0;
	gen107_cyclix_genvar = 32'd0;
	gen108_cyclix_genvar = 32'd0;
	gen24_rtl_var = 32'd0;
	gen109_cyclix_genvar = 32'd0;
	gen25_rtl_var = 32'd0;
	gen104_cyclix_genvar = 32'd0;
	gen105_cyclix_genvar = 32'd0;
	gen23_rtl_var = 32'd0;
	gen101_cyclix_genvar = 32'd0;
	gen102_cyclix_genvar = 32'd0;
	gen21_rtl_var = 32'd0;
	gen103_cyclix_genvar = 32'd0;
	gen22_rtl_var = 32'd0;
	gen92_cyclix_genvar = 32'd0;
	gen93_cyclix_genvar = 32'd0;
	gen17_rtl_var = 32'd0;
	gen100_cyclix_genvar = 32'd0;
	gen20_rtl_var = 32'd0;
	reg_input_buf_wr_en = gensticky_reg_input_buf_wr_en;
	reg_input_buf_rd_en = gensticky_reg_input_buf_rd_en;
	input_buf_mem[0] = gensticky_input_buf_mem[0];
	input_buf_mem[1] = gensticky_input_buf_mem[1];
	input_buf_mem[2] = gensticky_input_buf_mem[2];
	input_buf_mem[3] = gensticky_input_buf_mem[3];
	input_buf_mem[4] = gensticky_input_buf_mem[4];
	input_buf_wr_ptr = gensticky_input_buf_wr_ptr;
	reg_output_buf_wr_en = gensticky_reg_output_buf_wr_en;
	reg_output_buf_rd_en = gensticky_reg_output_buf_rd_en;
	output_buf_mem[0] = gensticky_output_buf_mem[0];
	output_buf_mem[1] = gensticky_output_buf_mem[1];
	output_buf_mem[2] = gensticky_output_buf_mem[2];
	output_buf_mem[3] = gensticky_output_buf_mem[3];
	output_buf_mem[4] = gensticky_output_buf_mem[4];
	output_buf_wr_ptr = gensticky_output_buf_wr_ptr;
	tick_period = gensticky_tick_period;
	tick = gensticky_tick;
	next_clk_count = gensticky_next_clk_count;
	clk_counter = gensticky_clk_counter;
	postsyn_neuron_counter_num = gensticky_postsyn_neuron_counter_num;
	presyn_neuron_counter_num = gensticky_presyn_neuron_counter_num;
	next_neuron_num = gensticky_next_neuron_num;
	next_postsyn_neuron_num = gensticky_next_postsyn_neuron_num;
	reg_weight_memory_wr_en = gensticky_reg_weight_memory_wr_en;
	reg_weight_memory_rd_en = gensticky_reg_weight_memory_rd_en;
	reg_cntl_sig = gensticky_reg_cntl_sig;
	reg_cntl_counter_sig = gensticky_reg_cntl_counter_sig;
	weight_memory[0][0] = gensticky_weight_memory[0][0];
	weight_memory[0][1] = gensticky_weight_memory[0][1];
	weight_memory[0][2] = gensticky_weight_memory[0][2];
	weight_memory[0][3] = gensticky_weight_memory[0][3];
	weight_memory[1][0] = gensticky_weight_memory[1][0];
	weight_memory[1][1] = gensticky_weight_memory[1][1];
	weight_memory[1][2] = gensticky_weight_memory[1][2];
	weight_memory[1][3] = gensticky_weight_memory[1][3];
	weight_memory[2][0] = gensticky_weight_memory[2][0];
	weight_memory[2][1] = gensticky_weight_memory[2][1];
	weight_memory[2][2] = gensticky_weight_memory[2][2];
	weight_memory[2][3] = gensticky_weight_memory[2][3];
	weight_memory[3][0] = gensticky_weight_memory[3][0];
	weight_memory[3][1] = gensticky_weight_memory[3][1];
	weight_memory[3][2] = gensticky_weight_memory[3][2];
	weight_memory[3][3] = gensticky_weight_memory[3][3];
	leakage = gensticky_leakage;
	threshold = gensticky_threshold;
	dynamic_mem[0] = gensticky_dynamic_mem[0];
	dynamic_mem[1] = gensticky_dynamic_mem[1];
	dynamic_mem[2] = gensticky_dynamic_mem[2];
	dynamic_mem[3] = gensticky_dynamic_mem[3];
	dynamic_mem[4] = gensticky_dynamic_mem[4];
	next_input_buf_counter_num = gensticky_next_input_buf_counter_num;
	input_buf_counter_num = gensticky_input_buf_counter_num;
	next_dynamic_mem_counter_num = gensticky_next_dynamic_mem_counter_num;
	dynamic_mem_counter_num = gensticky_dynamic_mem_counter_num;
	// Buffering globals
	// Processing dlychains
	// fifo_in buffering
	// subproc fifo_in buffering
	// Payload logic
	reg_input_buf_wr_en = input_buf_wr_en;
	reg_input_buf_rd_en = input_buf_rd_en;
	gen55_cyclix_genvar = (reg_input_buf_wr_en == 32'd1);
	gen56_cyclix_genvar = gen55_cyclix_genvar;
	gen0_rtl_var = gen56_cyclix_genvar;
	if (gen0_rtl_var)
		begin
		input_buf_mem[input_buf_wr_ptr] = input_buf_data_in;
		gen57_cyclix_genvar = (input_buf_wr_ptr + 32'd1);
		input_buf_wr_ptr = gen57_cyclix_genvar;
		end
	gen58_cyclix_genvar = (reg_input_buf_rd_en == 32'd1);
	gen59_cyclix_genvar = gen58_cyclix_genvar;
	gen1_rtl_var = gen59_cyclix_genvar;
	if (gen1_rtl_var)
		begin
		input_buf_data_out = input_buf_mem[input_buf_read_addr];
		end
	reg_output_buf_wr_en = output_buf_wr_en;
	reg_output_buf_rd_en = output_buf_rd_en;
	gen60_cyclix_genvar = (reg_input_buf_wr_en == 32'd1);
	gen61_cyclix_genvar = gen60_cyclix_genvar;
	gen2_rtl_var = gen61_cyclix_genvar;
	if (gen2_rtl_var)
		begin
		output_buf_mem[output_buf_wr_ptr] = output_buf_data_in;
		gen62_cyclix_genvar = (output_buf_wr_ptr + 32'd1);
		output_buf_wr_ptr = gen62_cyclix_genvar;
		end
	gen63_cyclix_genvar = (reg_output_buf_rd_en == 32'd1);
	gen64_cyclix_genvar = gen63_cyclix_genvar;
	gen3_rtl_var = gen64_cyclix_genvar;
	if (gen3_rtl_var)
		begin
		output_buf_data_out = output_buf_mem[output_buf_read_addr];
		end
	tick_period = 32'd500;
	gen65_cyclix_genvar = (tick_period != clk_counter);
	gen66_cyclix_genvar = gen65_cyclix_genvar;
	gen4_rtl_var = gen66_cyclix_genvar;
	if (gen4_rtl_var)
		begin
		tick = 32'd0;
		gen67_cyclix_genvar = (clk_counter + 32'd1);
		next_clk_count = gen67_cyclix_genvar;
		clk_counter = next_clk_count;
		end
	gen68_cyclix_genvar = 1'd0;
	gen68_cyclix_genvar = (gen68_cyclix_genvar || gen66_cyclix_genvar);
	gen68_cyclix_genvar = !gen68_cyclix_genvar;
	gen5_rtl_var = gen68_cyclix_genvar;
	if (gen5_rtl_var)
		begin
		tick = 32'd1;
		clk_counter = 32'd0;
		end
	dbg_tick = tick;
	dbg_clk_counter = clk_counter;
	dbg_tick_period = tick_period;
	dbg_presyn_neuron_counter_num = presyn_neuron_counter_num;
	dbg_postsyn_neuron_counter_num = postsyn_neuron_counter_num;
	gen69_cyclix_genvar = (reg_cntl_counter_sig == 32'd0);
	gen70_cyclix_genvar = gen69_cyclix_genvar;
	gen6_rtl_var = gen70_cyclix_genvar;
	if (gen6_rtl_var)
		begin
		postsyn_neuron_counter_num = 32'd0;
		presyn_neuron_counter_num = 32'd0;
		end
	gen71_cyclix_genvar = (reg_cntl_counter_sig == 32'd1);
	gen72_cyclix_genvar = gen71_cyclix_genvar;
	gen7_rtl_var = gen72_cyclix_genvar;
	if (gen7_rtl_var)
		begin
		gen73_cyclix_genvar = (postsyn_neuron_counter_num < 32'd4);
		gen74_cyclix_genvar = gen73_cyclix_genvar;
		gen8_rtl_var = gen74_cyclix_genvar;
		if (gen8_rtl_var)
			begin
			gen75_cyclix_genvar = (presyn_neuron_counter_num < 32'd4);
			gen76_cyclix_genvar = gen75_cyclix_genvar;
			gen9_rtl_var = gen76_cyclix_genvar;
			if (gen9_rtl_var)
				begin
				gen77_cyclix_genvar = (presyn_neuron_counter_num + 32'd1);
				next_neuron_num = gen77_cyclix_genvar;
				presyn_neuron_counter_num = next_neuron_num;
				end
			gen78_cyclix_genvar = 1'd0;
			gen78_cyclix_genvar = (gen78_cyclix_genvar || gen76_cyclix_genvar);
			gen78_cyclix_genvar = !gen78_cyclix_genvar;
			gen10_rtl_var = gen78_cyclix_genvar;
			if (gen10_rtl_var)
				begin
				gen79_cyclix_genvar = (postsyn_neuron_counter_num + 32'd1);
				next_postsyn_neuron_num = gen79_cyclix_genvar;
				postsyn_neuron_counter_num = next_postsyn_neuron_num;
				presyn_neuron_counter_num = 32'd0;
				end
			end
		end
	reg_weight_memory_wr_en = weight_memory_wr_en;
	reg_weight_memory_rd_en = weight_memory_rd_en;
	reg_cntl_sig = cntl_sig;
	gen80_cyclix_genvar = (reg_cntl_sig == 32'd0);
	gen81_cyclix_genvar = gen80_cyclix_genvar;
	gen11_rtl_var = gen81_cyclix_genvar;
	if (gen11_rtl_var)
		begin
		reg_cntl_counter_sig = 32'd0;
		end
	gen82_cyclix_genvar = (reg_cntl_sig == 32'd1);
	gen83_cyclix_genvar = gen82_cyclix_genvar;
	gen12_rtl_var = gen83_cyclix_genvar;
	if (gen12_rtl_var)
		begin
		reg_cntl_counter_sig = 32'd1;
		gen84_cyclix_genvar = (reg_weight_memory_wr_en == 32'd1);
		gen85_cyclix_genvar = gen84_cyclix_genvar;
		gen13_rtl_var = gen85_cyclix_genvar;
		if (gen13_rtl_var)
			begin
			weight_memory[postsyn_neuron_counter_num][presyn_neuron_counter_num] = weight_memory_data_in;
			end
		end
	gen86_cyclix_genvar = (reg_cntl_sig == 32'd2);
	gen87_cyclix_genvar = gen86_cyclix_genvar;
	gen14_rtl_var = gen87_cyclix_genvar;
	if (gen14_rtl_var)
		begin
		reg_cntl_counter_sig = 32'd1;
		gen88_cyclix_genvar = (reg_weight_memory_rd_en == 32'd1);
		gen89_cyclix_genvar = gen88_cyclix_genvar;
		gen15_rtl_var = gen89_cyclix_genvar;
		if (gen15_rtl_var)
			begin
			weight_memory_data_out = weight_memory[postsyn_neuron_counter_num][presyn_neuron_counter_num];
			end
		end
	leakage = 32'd1;
	threshold = 32'd2;
	gen90_cyclix_genvar = (reg_cntl_sig == 32'd3);
	gen91_cyclix_genvar = gen90_cyclix_genvar;
	gen16_rtl_var = gen91_cyclix_genvar;
	if (gen16_rtl_var)
		begin
		gen92_cyclix_genvar = (dynamic_mem_counter_num < 32'd4);
		gen93_cyclix_genvar = gen92_cyclix_genvar;
		gen17_rtl_var = gen93_cyclix_genvar;
		if (gen17_rtl_var)
			begin
			gen94_cyclix_genvar = (input_buf_counter_num < 32'd4);
			gen95_cyclix_genvar = gen94_cyclix_genvar;
			gen18_rtl_var = gen95_cyclix_genvar;
			if (gen18_rtl_var)
				begin
				gen96_cyclix_genvar = (input_buf_mem[input_buf_counter_num] == 32'd1);
				gen97_cyclix_genvar = gen96_cyclix_genvar;
				gen19_rtl_var = gen97_cyclix_genvar;
				if (gen19_rtl_var)
					begin
					dynamic_mem[dynamic_mem_counter_num] = weight_memory[dynamic_mem_counter_num][input_buf_counter_num];
					end
				gen98_cyclix_genvar = (input_buf_counter_num + 32'd1);
				next_input_buf_counter_num = gen98_cyclix_genvar;
				input_buf_counter_num = next_input_buf_counter_num;
				end
			gen99_cyclix_genvar = (dynamic_mem_counter_num + 32'd1);
			next_dynamic_mem_counter_num = gen99_cyclix_genvar;
			dynamic_mem_counter_num = next_dynamic_mem_counter_num;
			end
		gen100_cyclix_genvar = 1'd0;
		gen100_cyclix_genvar = (gen100_cyclix_genvar || gen93_cyclix_genvar);
		gen100_cyclix_genvar = !gen100_cyclix_genvar;
		gen20_rtl_var = gen100_cyclix_genvar;
		if (gen20_rtl_var)
			begin
			gen101_cyclix_genvar = (dynamic_mem_counter_num == 32'd4);
			gen102_cyclix_genvar = gen101_cyclix_genvar;
			gen21_rtl_var = gen102_cyclix_genvar;
			if (gen21_rtl_var)
				begin
				dynamic_mem_counter_num = 32'd0;
				end
			gen103_cyclix_genvar = 1'd0;
			gen103_cyclix_genvar = (gen103_cyclix_genvar || gen102_cyclix_genvar);
			gen103_cyclix_genvar = !gen103_cyclix_genvar;
			gen22_rtl_var = gen103_cyclix_genvar;
			if (gen22_rtl_var)
				begin
				gen104_cyclix_genvar = (dynamic_mem_counter_num < 32'd4);
				gen105_cyclix_genvar = gen104_cyclix_genvar;
				gen23_rtl_var = gen105_cyclix_genvar;
				if (gen23_rtl_var)
					begin
					gen106_cyclix_genvar = (dynamic_mem[dynamic_mem_counter_num] - leakage);
					dynamic_mem[dynamic_mem_counter_num] = gen106_cyclix_genvar;
					gen107_cyclix_genvar = (dynamic_mem[dynamic_mem_counter_num] < threshold);
					gen108_cyclix_genvar = gen107_cyclix_genvar;
					gen24_rtl_var = gen108_cyclix_genvar;
					if (gen24_rtl_var)
						begin
						output_buf_mem[dynamic_mem_counter_num] = 32'd0;
						end
					gen109_cyclix_genvar = 1'd0;
					gen109_cyclix_genvar = (gen109_cyclix_genvar || gen108_cyclix_genvar);
					gen109_cyclix_genvar = !gen109_cyclix_genvar;
					gen25_rtl_var = gen109_cyclix_genvar;
					if (gen25_rtl_var)
						begin
						output_buf_mem[dynamic_mem_counter_num] = 32'd1;
						end
					end
				end
			end
		end
	end


endmodule
