// ===========================================================
// RTL generated by ActiveCore framework
// Date: 2024-07-19 16:26:19
// Copyright Alexander Antonov <antonov.alex.alex@gmail.com>
// ===========================================================

`ifndef __Neuromorphic_design_h_
`define __Neuromorphic_design_h_

`endif // __Neuromorphic_design_h_
