// ===========================================================
// RTL generated by ActiveCore framework
// Date: 2025-10-26 22:40:33
// Copyright Alexander Antonov <antonov.alex.alex@gmail.com>
// ===========================================================

`ifndef __nm_core_top_h_
`define __nm_core_top_h_

`endif // __nm_core_top_h_
