// ===========================================================
// RTL generated by ActiveCore framework
// Date: 2025-11-21 12:50:36
// Copyright Alexander Antonov <antonov.alex.alex@gmail.com>
// ===========================================================

`ifndef __lif_core_h_
`define __lif_core_h_

`endif // __lif_core_h_
