#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Nov 21 19:38:51 MSK 2025
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 632b3d6badad44438e8c50f372734bc6 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_synapse_selector_behav xil_defaultlib.tb_synapse_selector xil_defaultlib.glbl -log elaborate.log"
xelab -wto 632b3d6badad44438e8c50f372734bc6 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_synapse_selector_behav xil_defaultlib.tb_synapse_selector xil_defaultlib.glbl -log elaborate.log

