// ===========================================================
// RTL generated by ActiveCore framework
// Date: 2024-09-28 15:42:31
// Copyright Alexander Antonov <antonov.alex.alex@gmail.com>
// ===========================================================

`ifndef __Neuromorphic_design_h_
`define __Neuromorphic_design_h_

`endif // __Neuromorphic_design_h_
